/* Shows that the tests catch a wrong module, before they are trusted to say
   a right one is right (derived from Hallym MIPS v2.5.0
   electron/tools/mutants.ts: the runner; the mutants are this app's).

     node tools/mutants.ts [FILTER]

   Each mutant below changes one thing in one file -- the text `find` must
   occur exactly once -- in a copy of src/, tests/, tools/ and packaging/ in a
   temporary directory, <tmp>/electron (node_modules/ is linked, not copied,
   and so are the repository's assets/ and tests/ next to it: the window's
   marks and characters, the test circuits), and runs the tests named for
   it there.  A mutant is KILLED when those tests fail; one that survives,
   or does not apply, fails this script.  Nothing in the working tree is
   touched.

   Tests named *.e2e.ts run the real window through Playwright (the copy's
   window script is bundled first); they need a display -- on Linux without
   one: xvfb-run -a -s '-screen 0 2400x1400x24' npm run test:mutants. */

import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');

interface Mutant {
  module: string;
  file: string;
  find: string;
  replace: string;
  tests: string[];
  what: string;
}

export const MUTANTS: Mutant[] = [
  // ---- JSON-RPC framing (src/main/rpc.ts)
  { module: 'rpc', file: 'src/main/rpc.ts', what: '\\r\\n lines keep their \\r',
    find: "p.endsWith('\\r') ? p.slice(0, -1) : p", replace: 'p', tests: ['tests/unit/rpc.test.ts'] },
  { module: 'rpc', file: 'src/main/rpc.ts', what: 'a character cut between chunks decoded on its own',
    find: 'this.decoder.decode(chunk, { stream: true })', replace: 'this.decoder.decode(chunk)', tests: ['tests/unit/rpc.test.ts'] },
  { module: 'rpc', file: 'src/main/rpc.ts', what: 'a request from the engine taken as a notification',
    find: "    if (hasId) return { kind: 'invalid', line, reason: 'a request from the engine (the engine only answers and notifies)' };\n", replace: '',
    tests: ['tests/unit/rpc.test.ts'] },
  // ---- the engine client (src/main/engine.ts)
  { module: 'engine', file: 'src/main/engine.ts', what: 'every request the same id',
    find: 'const id = this.nextId++;', replace: 'const id = this.nextId;', tests: ['tests/unit/engine.test.ts'] },
  { module: 'engine', file: 'src/main/engine.ts', what: 'an error answer taken as a result',
    find: '      p.reject(new EngineError(p.method, m.error));', replace: '      p.resolve(m.error);', tests: ['tests/unit/engine.test.ts'] },
  { module: 'engine', file: 'src/main/engine.ts', what: 'no restart after a crash',
    find: 'if (this.crashes.length > this.opts.maxRestarts) {', replace: 'if (true) {', tests: ['tests/unit/engine.test.ts'] },
  { module: 'engine', file: 'src/main/engine.ts', what: 'restarts without end',
    find: 'if (this.crashes.length > this.opts.maxRestarts) {', replace: 'if (false) {', tests: ['tests/unit/engine.test.ts'] },
  { module: 'engine', file: 'src/main/engine.ts', what: 'stderr not kept for the dialog',
    find: '      this.stderrTail.push(line);\n', replace: '', tests: ['tests/unit/engine.test.ts'] },
  { module: 'engine', file: 'src/main/engine.ts', what: 'answers not told (the journal and the shadow never hear of them)',
    find: "        this.emit('answer', { method: p.method, params: p.params, result: m.result, tag: p.tag });\n", replace: '',
    tests: ['tests/unit/engine.test.ts'] },
  { module: 'engine', file: 'src/main/engine.ts', what: 'engine.hello without the restarted engine\'s parameters',
    find: "{ ...this.opts.client, ...this.opts.helloParams?.() }", replace: 'this.opts.client', tests: ['tests/unit/engine.test.ts'] },
  // ---- crash recovery (src/main/recovery.ts, N-04)
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'edits replayed file by file, not in the order the engine answered them',
    find: '.sort((x, y) => x.e.seq - y.e.seq)', replace: '', tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'saving does not start the journal over',
    find: "Object.assign(f, { opened: { kind: 'path', path, readOnly }, fingerprint, circuits, entries: [], broken: null });",
    replace: "Object.assign(f, { opened: { kind: 'path', path, readOnly }, fingerprint, circuits, broken: null });", tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'a part matched without its attributes',
    find: '  return ka.length === Object.keys(b).length && ka.every((k) => a[k] === b[k]);', replace: '  return true;',
    tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'a restarted engine\'s ids not above the old ones',
    find: 'return floor > 0 ? { idFloor: floor } : {};', replace: 'return {};', tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'replaying again after the engine died while replaying',
    find: 'const replay = this.crashes <= 1;', replace: 'const replay = true;', tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'the window\'s calls not held back while recovering',
    find: 'settled(): Promise<void> { return this.gate?.promise ?? Promise.resolve(); }', replace: 'settled(): Promise<void> { return Promise.resolve(); }',
    tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'edits replayed onto a file changed on disk',
    find: "      else if (f.opened.kind === 'path' && this.fingerprint(f.opened.path) !== f.fingerprint) lost.set(f.fileId, 'changedOnDisk');\n", replace: '',
    tests: ['tests/unit/recovery.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'a file that failed its replay left half replayed',
    find: "        await this.call('file.close', { fileId: f.fileId }).catch((x) => { if (x instanceof EngineGone) throw x; });\n", replace: '',
    tests: ['tests/unit/recovery.test.ts'] },
  // ---- packaging and notices (tools/stage-engine.ts, NOTICE, About)
  { module: 'package', file: 'tools/stage-engine.ts', what: 'the runtime\'s links point into the build tree',
    find: 'verbatimSymlinks: true', replace: 'verbatimSymlinks: false', tests: ['tests/unit/package.test.ts'] },
  { module: 'package', file: 'tools/stage-engine.ts', what: 'packaged without the runtime, silently',
    find: "    [path.join(p.runtime, 'bin', javaExe), ':engine:runtime'],\n", replace: '', tests: ['tests/unit/package.test.ts'] },
  { module: 'notice', file: '../NOTICE', what: 'NOTICE without the runtime\'s license',
    find: '  License: GNU General Public License, version 2, with the Classpath\n           Exception', replace: '  License: GNU General Public License, version 2',
    tests: ['tests/unit/notice.test.ts'] },
  { module: 'notice', file: 'src/main/paths.ts', what: 'About > Licenses without the runtime',
    find: "  { name: 'LICENSE.openjdk.txt', title: 'OpenJDK runtime (Eclipse Temurin 21.0.12) — GNU General Public License, version 2, with the Classpath Exception' },\n",
    replace: '', tests: ['tests/unit/notice.test.ts'] },
  { module: 'recovered', file: 'src/renderer/app/logic/recovered.ts', what: 'the band does not say the simulation is back to Reset',
    find: '  if (any) band.push(RESET);', replace: '', tests: ['tests/unit/recovered.test.ts'] },
  { module: 'files', file: 'src/renderer/app/logic/files.ts', what: 'a reopened file keeps its old simulation state',
    find: '    f.sim = null;\n', replace: '', tests: ['tests/unit/files.test.ts'] },
  { module: 'engine-locate', file: 'src/main/engine-locate.ts', what: 'the JVM writes its performance file to the temp folder',
    find: "    '-XX:-UsePerfData',\n", replace: '', tests: ['tests/unit/engine-locate.test.ts'] },
  { module: 'engine-locate', file: 'src/main/engine-locate.ts', what: 'a -sources jar taken for the engine',
    find: "!/-(sources|javadoc|plain)\\.jar$/.test(n)", replace: 'true', tests: ['tests/unit/engine-locate.test.ts'] },
  { module: 'engine-locate', file: 'src/main/engine-locate.ts', what: 'the packaged app falls back to a Java of the PC\'s own',
    find: "    return { reason: `Java 런타임이 없습니다: ${path.join('runtime', 'bin', exe)}`, looked: bundled };\n", replace: '',
    tests: ['tests/unit/engine-locate.test.ts'] },
  { module: 'engine-locate', file: 'src/main/engine-locate.ts', what: 'the JVM\'s own warnings on stdout (the JSON-RPC lines)',
    find: "    '-Xlog:disable', '-Xlog:all=warning:stderr',\n", replace: '', tests: ['tests/unit/engine-locate.test.ts'] },
  { module: 'engine-locate', file: 'src/main/engine-locate.ts', what: 'the bundled runtime without its AppCDS archive',
    find: "    ...(archive ? [`-XX:SharedArchiveFile=${archive}`] : []),\n", replace: '', tests: ['tests/unit/engine-locate.test.ts'] },
  // ---- the lab-PC rule (src/main/run-folder.ts, main.ts)
  { module: 'run-folder', file: 'src/main/run-folder.ts', what: 'a running copy\'s folder removed',
    find: 'if (!pid || pid === self || isAlive(pid)) continue;', replace: 'if (!pid || pid === self) continue;', tests: ['tests/unit/run-folder.test.ts'] },
  { module: 'run-folder', file: 'src/main/run-folder.ts', what: 'a switch taken for the .circ',
    find: "    if (a.startsWith('-')) continue;\n", replace: '', tests: ['tests/unit/run-folder.test.ts'] },
  { module: 'lab-pc', file: 'src/main/main.ts', what: 'NSS\'s certificate store in the user\'s own folders (Linux)',
    find: "  process.env.XDG_DATA_HOME = path.join(runDir, 'data');\n", replace: '', tests: ['tests/e2e/labpc.e2e.ts'] },
  { module: 'lab-pc', file: 'src/main/main.ts', what: 'the run\'s folder left after quit',
    find: "    spawn(process.execPath, ['-e', removeAfterExitScript(process.pid, runDir)], {", replace: "    if (0) spawn(process.execPath, ['-e', removeAfterExitScript(process.pid, runDir)], {",
    tests: ['tests/e2e/labpc.e2e.ts'] },
  // ---- the window's logic (src/renderer/app/logic/)
  { module: 'layout', file: 'src/renderer/app/logic/layout.ts', what: 'the Canvas\'s least not kept',
    find: '  if (left + right > room) {', replace: '  if (false) {', tests: ['tests/unit/layout.test.ts'] },
  { module: 'layout', file: 'src/renderer/app/logic/layout.ts', what: 'narrow only under 900 px',
    find: 'const narrow = width < NARROW_PX;', replace: 'const narrow = width < 900;', tests: ['tests/unit/layout.test.ts'] },
  { module: 'files', file: 'src/renderer/app/logic/files.ts', what: 'closing shows the right neighbour',
    find: 'this.files[Math.max(0, i - 1)]', replace: 'this.files[i]', tests: ['tests/unit/files.test.ts'] },
  { module: 'facts', file: 'src/renderer/app/logic/facts.ts', what: 'tunnels in the order they come',
    find: "      .sort((a, b) => (a.label === '' ? 1 : b.label === '' ? -1 : a.label.localeCompare(b.label, 'en', { numeric: true }))),",
    replace: '', tests: ['tests/unit/facts.test.ts'] },
  { module: 'origin', file: 'src/renderer/shared/overlay.ts', what: 'a file copied from Hallym MIPS edited',
    find: 'export const TUTORIAL_DIM = { color: NAVY, alpha: 0.26 };', replace: 'export const TUTORIAL_DIM = { color: NAVY, alpha: 0.25 };',
    tests: ['tests/unit/origin.test.ts'] },
  // ---- Messages (src/renderer/app/logic/messages.ts, messages.ts; N-13, D-143)
  { module: 'messages', file: 'src/renderer/app/logic/messages.ts', what: 'an unknown kind dropped',
    find: '  return [...known.values(), other].filter((g) => g.messages.length > 0);', replace: '  return [...known.values()].filter((g) => g.messages.length > 0);',
    tests: ['tests/unit/messages.test.ts'] },
  { module: 'messages', file: 'src/renderer/app/logic/messages.ts', what: '"1 messages"',
    find: "message${n === 1 ? '' : 's'}", replace: 'messages', tests: ['tests/unit/messages.test.ts'] },
  { module: 'messages', file: 'src/renderer/app/logic/messages.ts', what: 'a static message sent with a cycle',
    find: "cycle: m.kind === 'dynamic' && typeof l.cycle === 'number' ? l.cycle : null,", replace: "cycle: typeof l.cycle === 'number' ? l.cycle : null,",
    tests: ['tests/unit/messages.test.ts'] },
  { module: 'messages', file: 'src/renderer/app/logic/messages.ts', what: 'the chosen message forgotten at every new list',
    find: '  return chosen !== null && list.some((m) => m.id === chosen) ? chosen : null;', replace: '  return null;',
    tests: ['tests/unit/messages.test.ts', 'tests/e2e/messages.e2e.ts'] },
  { module: 'messages', file: 'src/renderer/app/messages.ts', what: 'choosing a message sends nothing',
    find: '    o.onReveal(revealOf(state.fileId, m));', replace: '', tests: ['tests/e2e/messages.e2e.ts'] },
  { module: 'messages', file: 'src/renderer/app/messages.ts', what: 'the focus lost when the list comes again',
    find: '    if (focusId) box.querySelector', replace: '    if (!focusId) box.querySelector', tests: ['tests/e2e/messages.e2e.ts'] },
  { module: 'messages', file: 'src/renderer/app/app.ts', what: 'diag.changed not taken',
    find: '    diags.set(fileId, (p as unknown as DiagList).messages);', replace: '', tests: ['tests/e2e/messages.e2e.ts'] },
  { module: 'messages', file: 'src/renderer/app/app.css', what: 'a character on screen next to messages',
    find: 'body.messages-shown img.char { visibility: hidden; }', replace: '', tests: ['tests/e2e/messages.e2e.ts'] },
  { module: 'messages', file: 'tests/fake-engine/fake-engine.ts', what: 'the fake engine\'s ids not found from the fixture',
    find: "  const comp = (in_: Circuit | undefined, x: Place) => in_?.comps.find((k) => k.name === x.name && same(k.loc, x.loc))?.id ?? '';",
    replace: "  const comp = (_in: Circuit | undefined, _x: Place) => '';", tests: ['tests/unit/messages.test.ts'] },
  // ---- the window (e2e)
  // the editing tools on since N-08 (alpha.0 was view only, D-154), the versions About's only
  { module: 'window', file: 'src/renderer/app/app.ts', what: 'an editing tool left off',
    find: "const WORKING_TOOLS = new Set<string>(['Edit', 'Poke', 'Wire', 'Text', 'Pin', 'Tunnel', 'Probe']);", replace: "const WORKING_TOOLS = new Set<string>(['Edit', 'Poke', 'Wire', 'Text', 'Pin', 'Tunnel']);",
    tests: ['tests/e2e/files.e2e.ts'] },
  { module: 'window', file: 'src/renderer/app/app.ts', what: 'alpha.0: the engine\'s versions in the status bar again',
    find: "  // The engine's and Java's versions are About's only, not the student's status bar (D-154).\n",
    replace: "  if (engine.hello) parts.push(span('engine', `Logisim ${engine.hello.logisim} · Java ${engine.hello.java}`));\n",
    tests: ['tests/e2e/files.e2e.ts'] },
  { module: 'window', file: 'src/renderer/shared/welcome.ts', what: 'the first step\'s card shorter (no back row)',
    find: "    back.style.visibility = step === spec.first ? 'hidden' : 'visible';", replace: '    back.hidden = step === spec.first;',
    tests: ['tests/e2e/start.e2e.ts'] },
  { module: 'window', file: 'src/renderer/app/app.ts', what: 'a toolbar on the first screen',
    find: '  bar.showToolbar(f !== null);', replace: '  bar.showToolbar(true);', tests: ['tests/e2e/start.e2e.ts'] },
  { module: 'window', file: 'src/main/main.ts', what: 'the .circ on the command line ignored',
    find: '  const startup = circArgument(process.argv, process.cwd());', replace: '  const startup = circArgument([], process.cwd());',
    tests: ['tests/e2e/start.e2e.ts'] },
  { module: 'window', file: 'src/renderer/shared/ask.ts', what: 'a character next to an error',
    find: '    const withCharacter = q.character !== false;', replace: '    const withCharacter = true;', tests: ['tests/e2e/start.e2e.ts'] },
  { module: 'window', file: 'src/renderer/shared/ask.ts', what: 'a click outside closes the dialog',
    find: '    dialog.showModal();', replace: "    dialog.showModal();\n    dialog.addEventListener('click', (e) => { if (e.target === dialog) dialog.close(); });",
    tests: ['tests/e2e/window.e2e.ts'] },
  { module: 'window', file: 'src/renderer/app/app.ts', what: 'Attributes not moved into the left panel when narrow',
    find: '      upperPanel.append(attributesBody.root);', replace: '', tests: ['tests/e2e/layout.e2e.ts'] },
  { module: 'window', file: 'src/renderer/shared/titlebar.ts', what: 'the title bar never gives way',
    find: '  const fitsBar = () => tools.getBoundingClientRect().right <= end() + 0.5;', replace: '  const fitsBar = () => true;',
    tests: ['tests/e2e/layout.e2e.ts'] },
  { module: 'window', file: 'src/main/main.ts', what: 'the page may call any engine method (paths too)',
    find: "    if (!allowed.has(method)) throw new Error(`not a method the window may call: ${method}`);\n", replace: '',
    tests: ['tests/e2e/window.e2e.ts'] },
  { module: 'window', file: 'src/renderer/app/app.ts', what: 'Run follows Simulation Enabled instead of the clock',
    find: '  const ticking = f?.sim?.ticking ?? false;', replace: '  const ticking = f?.sim?.running ?? false;', tests: ['tests/e2e/engine.e2e.ts'] },
  { module: 'window', file: 'src/main/main.ts', what: 'the engine\'s notifications not forwarded',
    find: "    if (w && !w.isDestroyed()) w.webContents.send('engine:notify', method, params);\n", replace: '',
    tests: ['tests/e2e/engine.e2e.ts'] },
  { module: 'window', file: 'src/renderer/app/app.ts', what: 'a file that could not be opened again keeps its tab',
    find: '  for (const f of r.closed) { files.close(f.fileId); programs.drop(f.fileId); consoleView.drop(f.fileId); }\n', replace: '', tests: ['tests/e2e/recovery.e2e.ts'] },
  { module: 'window', file: 'src/main/main.ts', what: 'the window\'s calls not journaled (the recovery replays nothing)',
    find: '  return engine.call<T>(method, params, { tag: WINDOW });', replace: '  return engine.call<T>(method, params);',
    tests: ['tests/e2e/recovery.e2e.ts'] },
  // ---- the review round (D-135 points 14-17)
  { module: 'words', file: 'src/renderer/shared/shared.css', what: 'a character on screen next to an error',
    find: 'body.error-dialog img.char, body.band-shown img.char { visibility: hidden; }', replace: '', tests: ['tests/e2e/start.e2e.ts'] },
  { module: 'words', file: 'src/renderer/shared/shared.css', what: 'an English name broken across two lines',
    find: '.name { white-space: nowrap; }', replace: '', tests: ['tests/e2e/layout.e2e.ts'] },
  { module: 'words', file: 'src/renderer/app/app.ts', what: 'the engine\'s English shown for a file error',
    find: 'body: d.body, detail: d.detail', replace: 'body: (e as CallError).message, detail: d.detail', tests: ['tests/e2e/start.e2e.ts'] },
  { module: 'words', file: 'src/renderer/app/logic/facts.ts', what: '"1 wires"',
    find: "${n === 1 ? '' : 's'}", replace: 's', tests: ['tests/unit/facts.test.ts'] },
  { module: 'words', file: 'src/main/engine-locate.ts', what: 'the engine-failed sentence names another file than the one tried',
    find: 'path.basename(looked[0] ?? ENGINE_JAR)', replace: 'ENGINE_JAR', tests: ['tests/unit/engine-locate.test.ts'] },
  { module: 'origin', file: 'src/renderer/shared/ui.ts', what: 'a taken file that names the simulator core\'s op table',
    find: "import { h, icon } from './dom.ts';", replace: "import { h, icon } from './dom.ts'; // OP" + '_TABLE', tests: ['tests/unit/origin.test.ts'] },
  { module: 'window', file: 'src/renderer/app/app.ts', what: '한림 on screen',
    find: "'Hallym University 논리설계와 컴퓨터구조 실습을 위한 회로 편집·시뮬레이션 도구입니다.'",
    replace: "'한림대학교 논리설계와 컴퓨터구조 실습을 위한 회로 편집·시뮬레이션 도구입니다.'", tests: ['tests/unit/origin.test.ts'] },
  // ---- the program: Load Program, the summary, the band, the Console (N-16, D-147)
  { module: 'program', file: 'src/renderer/app/logic/program.ts', what: 'no band while a reload has failed',
    find: 'if (!f) return null;', replace: 'return null;', tests: ['tests/unit/program.test.ts'] },
  { module: 'program', file: 'src/renderer/app/logic/program.ts', what: 'the band gives the failure\'s time, not the last load\'s',
    find: 'const at = f.kept.loadedAt;', replace: 'const at = f.at;', tests: ['tests/unit/program.test.ts'] },
  { module: 'program', file: 'src/renderer/app/logic/program.ts', what: 'a changed source not the yellow row',
    find: 'warn: s.source.warn', replace: 'warn: false', tests: ['tests/unit/program.test.ts'] },
  { module: 'program', file: 'src/renderer/app/logic/console.ts', what: 'what the Console printed since is dropped',
    find: "+ (u.append ?? '')", replace: '', tests: ['tests/unit/program.test.ts'] },
  { module: 'program', file: 'src/main/program-path.ts', what: 'Load .hmx… for an old .s opens next to the .circ',
    find: 'if (source && source.trim()) {', replace: 'if (false) {', tests: ['tests/unit/program.test.ts'] },
  { module: 'program', file: 'src/main/main.ts', what: 'Load Program\'s dialog shows every file',
    find: 'filters: [IMAGE_FILTER],', replace: "filters: [IMAGE_FILTER, { name: 'All files', extensions: ['*'] }],", tests: ['tests/e2e/program.e2e.ts'] },
  { module: 'program', file: 'src/renderer/app/app.ts', what: 'no band while a reload has failed (the window)',
    find: "if (b) programBand.show(b.text, 'warn', b.title);", replace: 'if (b) void 0;', tests: ['tests/e2e/program.e2e.ts'] },
  { module: 'program', file: 'src/renderer/app/program.ts', what: 'a character next to a file that cannot be loaded',
    find: "cls: 'loaderror', character: false,", replace: "cls: 'loaderror', character: true,", tests: ['tests/e2e/program.e2e.ts'] },
  { module: 'program', file: 'src/renderer/app/program.ts', what: 'the answer to "which memory?" not sent',
    find: 'o = { ...o, again: true, picks: { ...(o.picks ?? {}), [r.choose.kind]: id } };', replace: 'o = { ...o, again: true };',
    tests: ['tests/e2e/program.e2e.ts'] },
  { module: 'program', file: 'src/main/recovery.ts', what: 'a program load not replayed after an engine crash',
    find: " || method === 'mips.load'", replace: '', tests: ['tests/e2e/program.e2e.ts'] },
  { module: 'program', file: 'src/renderer/app/app.ts', what: 'the Console\'s stream not shown',
    find: 'if (files.get(String(p.fileId))) consoleView.update(p as unknown as ConsoleUpdate);', replace: 'void 0;', tests: ['tests/e2e/program.e2e.ts'] },
  // ---- the Canvas (src/renderer/canvas, N-05, N-06, D-137)
  { module: 'canvas', file: 'src/renderer/canvas/parts/gates.ts', what: 'a gate\'s input lines left out (its ports not reached)',
    find: 'if (end > px + 0.01) shapes.push(stubLocal(', replace: 'if (false) shapes.push(stubLocal(', tests: ['tests/unit/canvas-geometry.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/parts/subcircuit.ts', what: 'a subcircuit\'s appearance placed about the wrong anchor',
    find: 'ox: p.loc[0] - (ax * cos - ay * sin)', replace: 'ox: p.loc[0] - (ax * cos + ay * sin)', tests: ['tests/unit/canvas-geometry.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/tokens.ts', what: 'the Canvas\'s 1 another green than the legend\'s',
    find: "  vOne: '#22b14c',", replace: "  vOne: '#22b14d',", tests: ['tests/unit/canvas-registry.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/wires.ts', what: 'a jump where wires connect',
    find: 'if (inside(v, at) && !dots.has(key(at)))', replace: 'if (inside(v, at))', tests: ['tests/unit/canvas-scene.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/labels.ts', what: 'a label chip placed on a wire',
    find: 'let chosen = all.find((b) => !obs.hits(inflate(b, CLEAR))) ?? null;', replace: 'let chosen = all[0] ?? null;', tests: ['tests/unit/canvas-labels.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/view.ts', what: 'Ctrl+wheel zooms about the corner, not the pointer',
    find: 'return { zoom: z, x: cx - at[0] / z, y: cy - at[1] / z };', replace: 'return { zoom: z, x: v.x, y: v.y };', tests: ['tests/unit/canvas-scene.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/layers.ts', what: 'the fills painted last (a part hidden by another\'s fill)',
    find: '  for (const c of ordered) for (const s of shapesOf(c).base) out.push({ part: c, shape: s, pass: \'base\' });\n  for (const c of ordered) for (const s of shapesOf(c).top) out.push({ part: c, shape: s, pass: \'top\' });',
    replace: '  for (const c of ordered) for (const s of shapesOf(c).top) out.push({ part: c, shape: s, pass: \'top\' });\n  for (const c of ordered) for (const s of shapesOf(c).base) out.push({ part: c, shape: s, pass: \'base\' });',
    tests: ['tests/unit/canvas-layers.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/labels.ts', what: 'a port name written right on its wire',
    find: '    if (clear.some((t) => boxesMeet(t, box))) continue;   // never on or next to a wire\n', replace: '', tests: ['tests/unit/canvas-labels.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/view.ts', what: 'fit at the 25 % floor centred (cutting the circuit\'s edges)',
    find: '    : lo - FIT_MARGIN / zoom);', replace: '    : (lo + hi) / 2 - size / 2 / zoom);', tests: ['tests/unit/canvas-scene.test.ts'] },
  { module: 'canvas', file: 'src/renderer/canvas/svg.ts', what: 'an exported arc drawn the other way round',
    find: 'const flag = s[6] ? 0 : 1;', replace: 'const flag = s[6] ? 1 : 0;', tests: ['tests/unit/canvas-draw.test.ts'] },
  // ---- the Cycle View's models (N-14: src/renderer/app/logic/cycle.ts, registers.ts, memory.ts, values.ts)
  { module: 'cycle', file: 'src/renderer/app/logic/cycle.ts', what: 'the table jumps although the cycle on show is in the window shown',
    find: 'if (before && cycle >= before.from && cycle <= before.from + n - 1 && before.from >= first) return clamp(before.from);', replace: '',
    tests: ['tests/unit/cycle.test.ts'] },
  { module: 'cycle', file: 'src/renderer/app/logic/cycle.ts', what: 'no edge where a wave changes at a column\'s start',
    find: 'edgeIn: i > 0 && prev !== a', replace: 'edgeIn: false', tests: ['tests/unit/cycle.test.ts'] },
  { module: 'cycle', file: 'src/renderer/app/logic/cycle.ts', what: 'a past cycle said as the latest',
    find: 'cycle: s.past ? `Cycle ${c} / ${s.last.toLocaleString(\'en-US\')}` : `Cycle ${c}`', replace: 'cycle: `Cycle ${c}`', tests: ['tests/unit/cycle.test.ts'] },
  { module: 'cycle', file: 'src/renderer/app/logic/cycle.ts', what: 'Run Until without a limit on its cycles',
    find: 'max < 1 || max > 1_000_000', replace: 'max < 1', tests: ['tests/unit/cycle.test.ts'] },
  { module: 'cycle', file: 'src/renderer/app/logic/cycle.ts', what: 'an instruction name sent as typed',
    find: "value: v.toLowerCase(), maxCycles: max } };", replace: 'value: v, maxCycles: max } };', tests: ['tests/unit/cycle.test.ts'] },
  { module: 'values', file: 'src/renderer/app/logic/values.ts', what: 'an E bit shown as x',
    find: "nibble.includes('E') ? 'E' : nibble.includes('x') ? 'x'", replace: "nibble.includes('x') || nibble.includes('E') ? 'x'", tests: ['tests/unit/cycle.test.ts'] },
  { module: 'values', file: 'src/renderer/app/logic/values.ts', what: 'decimal without its sign',
    find: 'return u >= 2 ** (w - 1) ? u - 2 ** w : u;', replace: 'return u;', tests: ['tests/unit/cycle.test.ts'] },
  { module: 'registers', file: 'src/renderer/app/logic/registers.ts', what: 'PC painted as the register that just changed',
    find: "changed: r.changed && r.key !== 'PC',", replace: 'changed: r.changed,', tests: ['tests/unit/panels.test.ts'] },
  { module: 'registers', file: 'src/renderer/app/logic/registers.ts', what: 'Mark as PC does not rebuild the rows',
    find: '|${v.markedPc}`', replace: '`', tests: ['tests/unit/panels.test.ts'] },
  { module: 'memory', file: 'src/renderer/app/logic/memory.ts', what: 'a word\'s characters big-endian',
    find: 'printable((v >>> (8 * k)) & 0xff)', replace: 'printable((v >>> (8 * (3 - k))) & 0xff)', tests: ['tests/unit/panels.test.ts'] },
  { module: 'memory', file: 'src/renderer/app/logic/memory.ts', what: '$sp tints the line\'s first word only',
    find: 'pointed.some((p) => p.at >= a && p.at < a + 4)', replace: 'pointed.some((p) => p.at === from)', tests: ['tests/unit/panels.test.ts'] },
  { module: 'cycle', file: 'src/renderer/app/logic/cycle.ts', what: 'the pinned rows kept after their message went',
    find: 'pinned !== undefined && !ids.includes(pinned)', replace: 'false', tests: ['tests/unit/cycle.test.ts'] },
  { module: 'recovery', file: 'src/main/recovery.ts', what: 'Mark as PC, the register file and its mapping not journaled',
    find: ' || MODEL_EDITS.includes(method)', replace: '', tests: ['tests/unit/recovery.test.ts'] },
  // ---- the Windows installer (tools/package-config.ts, packaging/installer.nsh; N-23, D-148)
  { module: 'installer', file: 'tools/package-config.ts', what: 'a desktop shortcut',
    find: 'createDesktopShortcut: false,', replace: 'createDesktopShortcut: true,', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: 'a one-click installer (no pages; D-155)',
    find: 'oneClick: false,', replace: 'oneClick: true,', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: 'for all users (an administrator)',
    find: 'perMachine: false,', replace: 'perMachine: true,', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: 'a block map beside the installer (differential updates)',
    find: '      differentialPackage: false,\n', replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: '.circ associated with the program',
    find: '    // No fileAssociations, no protocols', replace: "    fileAssociations: [{ ext: 'circ', name: 'Logisim circuit' }],\n    // No fileAssociations, no protocols",
    tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: 'a zip of the program beside the installer',
    find: "target: [{ target: 'nsis', arch: ['x64'] }]", replace: "target: [{ target: 'nsis', arch: ['x64'] }, { target: 'zip', arch: ['x64'] }]",
    tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the v1.0.x MSI never looked for',
    find: '  !insertmacro hcsRemoveV1Msi\n', replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'another UpgradeCode than the 1.0.x MSI\'s',
    find: '{6206F18C-D7FA-366B-98DA-E7980F6083D6}', replace: '{6206F18C-D7FA-366B-98DA-E7980F6083D7}', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'msiexec with its own dialogs',
    find: '/x $R1 /qn /norestart', replace: '/x $R1', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'a notice that waits in a silent install',
    find: ': ${HCS_V1_MSI_NAME}" /SD IDOK', replace: ': ${HCS_V1_MSI_NAME}"', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'a particle after the program\'s name',
    find: '다음 프로그램을 제거합니다: ${PRODUCT_NAME}', replace: '${PRODUCT_NAME}을(를) 제거합니다', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the installer\'s copy for an updater kept',
    find: '  RMDir "$LOCALAPPDATA\\hallym-circuit-studio-updater"\n', replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the uninstaller\'s cleanup run in the install folder (an upgrade)',
    find: '  ${AndIf} "$EXEDIR" != "$INSTDIR"\n', replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the cleanup started in the install folder (kept from removal)',
    find: 'i 0x08000000, p 0, w "$SYSDIR", p R4', replace: 'i 0x08000000, p 0, p 0, p R4', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the uninstaller\'s copy left in %TEMP%',
    find: '!macro customUnInstall\n  !insertmacro hcsRemoveUninstallerCopy\n', replace: '!macro customUnInstall\n', tests: ['tests/unit/package-config.test.ts'] },
  // ---- the assisted installer's pages, words and colours (D-155; Hallym MIPS 2.5.0)
  { module: 'installer', file: 'tools/package-config.ts', what: 'the folder can be chosen',
    find: 'allowToChangeInstallationDirectory: false,', replace: 'allowToChangeInstallationDirectory: true,', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: 'the finish page without 지금 실행하기',
    find: 'runAfterFinish: true,', replace: 'runAfterFinish: false,', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/package-config.ts', what: 'electron-builder\'s own side band drawing',
    find: "      installerSidebar: path.join(p.root, 'packaging/installerSidebar.bmp'),\n", replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the "for all users or only me" page',
    find: '  StrCpy $isForceCurrentInstall "1"\n', replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the finish page without its run box',
    find: '  !define MUI_FINISHPAGE_RUN\n', replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the run box not ticked',
    find: '  !define MUI_FINISHPAGE_RUN_TEXT "지금 실행하기"\n', replace: '  !define MUI_FINISHPAGE_RUN_TEXT "지금 실행하기"\n  !define MUI_FINISHPAGE_RUN_NOTCHECKED\n', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'a particle after the program\'s name on the finish page',
    find: 'Hallym Circuit Studio 설치를 마쳤습니다.', replace: 'Hallym Circuit Studio를 설치했습니다.', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the progress bar in another colour than the app\'s blue',
    find: '!define HCS_BAR_COLOUR 0xA55500', replace: '!define HCS_BAR_COLOUR 0x00A555', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the progress bar keeps its visual style (and Windows\' green)',
    find: "  System::Call 'uxtheme::SetWindowTheme(p r0, w \"\", w \"\")'\n", replace: '', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'packaging/installer.nsh', what: 'the uninstaller with electron-builder\'s welcome page',
    find: '  !define MUI_PAGE_HEADER_TEXT "제거하는 중"\n', replace: '  !insertmacro MUI_UNPAGE_WELCOME\n  !define MUI_PAGE_HEADER_TEXT "제거하는 중"\n', tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/windows/check-installer-ui.ps1', what: 'the guided uninstall not compared with the state before',
    find: "  StateDiff 'ui-before' 'ui-uninstalled' 'uninstalled' 'ui-uninstall'", replace: "  # (not compared)", tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer', file: 'tools/windows/check-installer-ui.ps1', what: 'no control period before the guided install',
    find: "Control 'ui-install' 45 'ui-before'", replace: "Snap 'ui-before'", tests: ['tests/unit/package-config.test.ts'] },
  { module: 'installer art', file: 'tools/installer-art.py', what: 'the symbol stretched to a square',
    find: 'svg2png(url=SYMBOL, output_width=sym_w)', replace: 'svg2png(url=SYMBOL, output_width=sym_w, output_height=sym_w)', tests: ['tests/unit/installer-art.test.ts'] },
  { module: 'installer art', file: 'tools/installer-art.py', what: 'Korean in the band',
    find: "NAME = 'Hallym Circuit Studio'", replace: "NAME = '한림 Circuit Studio'", tests: ['tests/unit/installer-art.test.ts'] },
  // ---- the first screen's video (src/renderer/shared/backdrop.ts, tools/start-video.ts; D-155, Hallym MIPS 2.5.0)
  { module: 'first screen', file: 'src/renderer/shared/welcome.ts', what: 'each step builds its own background',
    find: '    actions.dataset.step = step;\n', replace: "    actions.dataset.step = step;\n    if (step !== spec.first) document.querySelector('.wback')?.replaceWith(backdrop().root);\n",
    tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/backdrop.ts', what: 'the video\'s sound back',
    find: '  clip.muted = true;\n', replace: '  clip.muted = false;\n', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/backdrop.ts', what: 'the video under prefers-reduced-motion',
    find: 'if (!shown || reduce.matches ||', replace: 'if (!shown ||', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/backdrop.ts', what: 'the video goes on under a circuit',
    find: 'if (on !== shown) { shown = on; update(); }', replace: 'if (on) { shown = on; update(); }', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/app/app.ts', what: 'the video never started',
    find: '  start.show(!stage.hidden);', replace: '  void stage;', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/shared.css', what: 'a clip that cannot play leaves the still',
    find: '.wback.failed img, .wback.failed video,', replace: '.wback.failed video,', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/shared.css', what: 'white under the video',
    find: 'pointer-events: none; background: var(--navy); }', replace: 'pointer-events: none; background: var(--white); }', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/shared.css', what: 'the video untinted',
    find: ".wback::after { content: '';", replace: ".wback::after { display: none; content: '';", tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/shared.css', what: 'the video unblurred',
    find: 'object-fit: cover; filter: blur(3px) saturate(.85);', replace: 'object-fit: cover;', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/shared/shared.css', what: 'the card see-through',
    find: '  background: var(--white); border: 1px solid var(--border); border-radius: 14px; padding: 36px 40px; box-shadow',
    replace: '  background: rgba(255,255,255,.82); border: 1px solid var(--border); border-radius: 14px; padding: 36px 40px; box-shadow', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'src/renderer/app/index.html', what: 'the page may not load media',
    find: " media-src 'self';", replace: '', tests: ['tests/e2e/backdrop.e2e.ts'] },
  { module: 'first screen', file: 'tools/start-video.ts', what: 'the clip made with the source\'s sound',
    find: "'-map', '[v]', '-an',", replace: "'-map', '[v]', '-map', '0:a?',", tests: ['tests/unit/start-clip.test.ts'] },
  { module: 'first screen', file: 'tools/start-video.ts', what: 'the slowed clip without the frames in between',
    find: 'minterpolate=fps=${FPS}:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1', replace: 'fps=${FPS}', tests: ['tests/unit/start-clip.test.ts'] },
  // ---- what a release may carry (tools/release-assets.ts; N-23)
  { module: 'release', file: 'tools/release-assets.ts', what: 'an MSI taken for something else',
    find: "else if (lower.endsWith('.msi'))", replace: "else if (lower.endsWith('.msi') && false)", tests: ['tests/unit/release-assets.test.ts'] },
  { module: 'release', file: 'tools/release-assets.ts', what: 'any zip taken for track A\'s',
    find: "`^hcs-mips-${escape(version)}-(windows|linux)\\\\.zip$`", replace: "`^.*\\\\.zip$`", tests: ['tests/unit/release-assets.test.ts'] },
  { module: 'release', file: 'tools/release-assets.ts', what: 'a release without the setup exe',
    find: '  if (!names.includes(setup)) problems.push', replace: '  if (false) problems.push', tests: ['tests/unit/release-assets.test.ts'] },
  { module: 'release', file: 'tools/release-assets.ts', what: 'the 1.0.x releases checked too',
    find: "return Number(version.split('.')[0]) >= 2;", replace: "return Number(version.split('.')[0]) >= 1;", tests: ['tests/unit/release-assets.test.ts'] },
  // ---- what a run or an install may leave on Windows (tools/windows/state.ts; N-23)
  { module: 'state', file: 'tools/windows/state.ts', what: 'any folder in %TEMP% taken for Playwright\'s',
    find: 'path: /^TEMP\\\\playwright-artifacts-[A-Za-z0-9]+$/', replace: 'path: /^TEMP\\\\.*$/', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'something in Playwright\'s folder taken for the folder',
    find: 'path: /^TEMP\\\\playwright-artifacts-[A-Za-z0-9]+$/', replace: 'path: /^TEMP\\\\playwright-artifacts-[A-Za-z0-9]+(\\\\.*)?$/', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'Windows\' noise excusing a change that names this program',
    find: "if (control !== undefined && !namesUs(c)) return { kind: 'noise', control };", replace: "if (control !== undefined) return { kind: 'noise', control };", tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'the measured noise ignored',
    find: "if (control !== undefined && !namesUs(c)) return { kind: 'noise', control };", replace: "if (false) return { kind: 'noise', control: control! };", tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'noise matched by its folder, not its exact place',
    find: 'const control = noise.get(noiseKey(c));',
    replace: "const up = (k: string) => k.slice(0, k.lastIndexOf('\\\\')); const control = noise.get(noiseKey(c)) ?? [...noise].find(([k]) => up(k) === up(noiseKey(c)))?.[1];",
    tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'noise matched by its path in any place (%TEMP%, the files, the registry)',
    find: "export const noiseKey = (c: Pick<Change, 'where' | 'path'>): string => `${c.where}\\t${c.path}`;",
    replace: "export const noiseKey = (c: Pick<Change, 'where' | 'path'>): string => c.path;", tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'only the first control period\'s noise',
    find: 'for (const f of files) for (const c of f.changes)', replace: 'for (const f of files.slice(0, 1)) for (const c of f.changes)', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'a control period not measured taken for no noise',
    find: "return files.map((f) => JSON.parse(readFileSync(f, 'utf8')) as NoiseFile);",
    replace: "return files.filter((f) => existsSync(f)).map((f) => JSON.parse(readFileSync(f, 'utf8')) as NoiseFile);", tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'every control period in the folder excusing a check',
    find: "return files.map((f) => JSON.parse(readFileSync(f, 'utf8')) as NoiseFile);",
    replace: "const d = path.dirname(files[0] ?? '.'); return readdirSync(d).filter((f) => /^noise-/.test(f)).map((f) => JSON.parse(readFileSync(path.join(d, f), 'utf8')) as NoiseFile);", tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'Windows Search\'s whole settings folder taken for its hive\'s log',
    find: 'Settings\\\\\\\\settings\\\\.dat\\\\.LOG[12]$', replace: 'Settings\\\\\\\\.*$', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'any data taken for the quiet-hours telemetry time',
    find: 'data: /^REG_BINARY [0-9A-F]{16}$/,', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'any file beside the Classes hive taken for its files',
    find: 'UsrClass\\.dat(\\.LOG[12])?$/', replace: 'UsrClass\\.dat.*$/', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'any program\'s Search icon taken for this one\'s',
    find: 'AppIconCache\\\\\\\\100\\\\\\\\kr_ac_hallym_circuit-studio$', replace: 'AppIconCache\\\\\\\\100\\\\\\\\.*$', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'a change naming this program taken for Windows\' own',
    find: '    if (!k.mayName && namesUs(c)) continue;\n', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'any UserAssist value taken for this program\'s counter',
    find: 'Count :: xe\\.np\\.unyylz\\.pvephvg-fghqvb$/', replace: 'Count :: .*$/', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'an installer\'s place taken for a Windows store',
    find: '    if (k.path === WINDOWS_STORES && INSTALLER_PLACES.test(c.path)) continue;\n', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'the .circ open-with list taken for a Windows store',
    find: '|Microsoft\\\\Windows\\\\CurrentVersion\\\\Explorer\\\\FileExts\\\\\\.circ', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'Windows\' stores let through in a run',
    find: 'in: INSTALLING, path: WINDOWS_STORES,', replace: 'in: ALL, path: WINDOWS_STORES,', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'any WinTrust state taken for its default',
    find: 'data: /^REG_DWORD 0x23c00$/,', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'an opened spelling language taken for the empty key',
    find: 'keyOnly: true, path: /^HKCU\\\\Software\\\\Microsoft\\\\Spelling$/', replace: 'path: /^HKCU\\\\Software\\\\Microsoft\\\\Spelling(\\\\.*)?$/', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'a value where only an empty key was seen',
    find: '    if (k.keyOnly && c.after !== \'key\') continue;\n', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'a file where only Windows\' folder was seen',
    find: '    if (k.dirOnly && c.after !== \'dir\') continue;\n', replace: '', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'an install may add any registry key',
    find: 'return UNINSTALL_ENTRY.test(c.path) || INSTALL_RECORD.test(c.path);', replace: 'return true;', tests: ['tests/unit/state.test.ts'] },
  { module: 'state', file: 'tools/windows/state.ts', what: 'the default value named by the system\'s language',
    find: '/^\\((Default|기본값)\\)$/.test(m[1]) ? \'(Default)\' : m[1]', replace: 'm[1]', tests: ['tests/unit/state.test.ts'] },
  { module: 'labpc', file: 'src/main/run-folder.ts', what: 'the spell checker on',
    find: 'browser: { enable_spellchecking: false }', replace: 'browser: { enable_spellchecking: true }', tests: ['tests/e2e/labpc.e2e.ts'] },
  { module: 'labpc', file: 'src/main/run-folder.ts', what: 'the OS language\'s spell checker opened (an empty language list)',
    find: "spellcheck: { dictionaries: ['zz'] }", replace: 'spellcheck: { dictionaries: [] }', tests: ['tests/e2e/labpc.e2e.ts'] },
  { module: 'run-folder', file: 'src/main/run-folder.ts', what: 'the runs\' folder left in the temp folder',
    find: 'try{rmdirSync(runs)}catch{}', replace: '', tests: ['tests/unit/run-folder.test.ts'] },
  // ---- finding and placing (N-12, D-150)
  { module: 'find', file: 'src/renderer/app/logic/search.ts', what: 'the same name no better than its start',
    find: 'if (a === q) best = Math.max(best, 100);', replace: 'if (a === q) best = Math.max(best, 80);', tests: ['tests/unit/search.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/search.ts', what: 'favourites not moved up',
    find: 'if (s.favorites?.includes(key)) b += 30;', replace: '', tests: ['tests/unit/search.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/search.ts', what: 'a number the original would not take kept (an AND gate of one input)',
    find: 'if (!Number.isSafeInteger(n) || n < a.min || n > a.max) return null;', replace: 'if (!Number.isSafeInteger(n)) return null;', tests: ['tests/unit/search.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/search.ts', what: 'the circuit on show offered to be placed in itself',
    find: 'if (t.circuitId === s.current && !s.includeCurrent) continue;', replace: '', tests: ['tests/unit/search.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/search.ts', what: 'every command offered, runnable or not',
    find: '    if (!s.commands?.includes(c.id)) continue;\n', replace: '', tests: ['tests/unit/search.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/splitter.ts', what: 'the top arm the low bits with MSB on top',
    find: '(msbOnTop ? msb(q) - msb(p) : msb(p) - msb(q))', replace: '(msbOnTop ? msb(p) - msb(q) : msb(q) - msb(p))', tests: ['tests/unit/splitter-spec.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/splitter.ts', what: 'one bit in two arms let through',
    find: "      if (used[b]) return { kind: 'twice', bit: b };\n", replace: '', tests: ['tests/unit/splitter-spec.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/splitter.ts', what: 'the strip splits an arm a bit too low',
    find: 'arms.push(arm(x.bits.filter((bit) => bit >= bitLeft), x.name));', replace: 'arms.push(arm(x.bits.filter((bit) => bit > bitLeft), x.name));', tests: ['tests/unit/splitter-spec.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/tunnels.ts', what: 'every press the first tunnel of the name',
    find: 'this.at = e.name === this.name ? (this.at + 1) % e.ids.length : 0;', replace: 'this.at = 0;', tests: ['tests/unit/find-panels.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/tunnels.ts', what: 'a pair of tunnels marked lone',
    find: 'lone: list.length === 1,', replace: 'lone: list.length <= 2,', tests: ['tests/unit/find-panels.test.ts'] },
  { module: 'find', file: 'src/renderer/canvas/labels.ts', what: 'the colour the student picked for a tunnel not drawn',
    find: "t.push({ name: c.attrs.label ?? '', at: c.loc, color: c.ext?.color });", replace: "t.push({ name: c.attrs.label ?? '', at: c.loc });", tests: ['tests/unit/canvas-labels.test.ts'] },
  { module: 'find', file: 'src/renderer/canvas/labels.ts', what: 'an arm\'s name left off its chip',
    find: "return { q, range: r, named: r && names[k] ? `${r} ${names[k]}` : r };", replace: 'return { q, range: r, named: r };', tests: ['tests/unit/canvas-labels.test.ts'] },
  { module: 'find', file: 'src/renderer/canvas/labels.ts', what: 'an arm\'s name drawn over the part next to the splitter',
    find: 'const useNames = withNames.some((t, k) => t !== plain[k]) && isFree(namedBoxes);', replace: 'const useNames = withNames.some((t, k) => t !== plain[k]);', tests: ['tests/unit/canvas-labels.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/find.ts', what: 'a group of several goes instead of opening',
    find: "return row.group.places.length > 1 ? 'toggle' : 'none';", replace: "return row.group.places.length > 1 ? 'go' : 'none';", tests: ['tests/unit/find-panels.test.ts'] },
  { module: 'find', file: 'src/renderer/app/logic/minimap.ts', what: 'a press on the Minimap read back to the wrong circuit point',
    find: 'export const fromMap = (f: Fit, m: [number, number]): [number, number] => [(m[0] - f.ox) / f.scale, (m[1] - f.oy) / f.scale];',
    replace: 'export const fromMap = (f: Fit, m: [number, number]): [number, number] => [(m[0] + f.ox) / f.scale, (m[1] - f.oy) / f.scale];', tests: ['tests/unit/find-panels.test.ts'] },
  { module: 'find', file: 'src/renderer/app/app.ts', what: 'a part placed here although the placement flow took it (the window)',
    find: '  if (emitPlaceTool(p) || !p.at) return;', replace: '  emitPlaceTool(p);\n  if (!p.at) return;', tests: ['tests/e2e/find.e2e.ts'] },
  { module: 'find', file: 'src/renderer/canvas/canvas.ts', what: 'a found part marked in the error colour (the window)',
    find: "tone: r.tone ?? 'error' };", replace: "tone: 'error' };", tests: ['tests/e2e/find.e2e.ts'] },
  // ---- the Canvas's overlays (N-15, D-151)
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a signed bus value read as unsigned',
    find: "(v[0] === '1' ? u - (1n << BigInt(v.length)) : u)", replace: 'u', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a one-bit wire gets a value chip',
    find: "v.length < 2 || ", replace: '', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a net named after a pin before its tunnel',
    find: 'for (const s of [tunnels, drivers, pins])', replace: 'for (const s of [pins, drivers, tunnels])', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'the influence never comes back to all steps',
    find: 'return next >= max ? -1 : next;', replace: 'return next;', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'the dashes run against the signal',
    find: 'const first = (((t - s.start) % period) + period) % period;', replace: 'const first = (((s.start - t) % period) + period) % period;', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a tunnel arc that ignores the bodies it crosses',
    find: 'if (blockers.some((b) => inBox(b, p))) hits++;', replace: '', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'an end\'s label over a part',
    find: 'if (hard.some((o) => boxesMeet(o, box)) || placed.some((o) => boxesMeet(o, box))) continue;', replace: 'if (placed.some((o) => boxesMeet(o, box))) continue;', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a click on a part\'s output port flows from all its outputs',
    find: 'return { componentId: part, port: outputNear(c, at) };', replace: 'return { componentId: part, port: -1 };', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a new memo tight around the chosen parts (no margin)',
    find: 'const x = snap(x0 - 20), y = snap(y0 - 20);', replace: 'const x = snap(x0), y = snap(y0);', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/memos.ts', what: 'the largest memo under the point, not the smallest',
    find: 'm.w * m.h < best.w * best.h', replace: 'm.w * m.h > best.w * best.h', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/memos.ts', what: 'a memo\'s word over a chip',
    find: 'if (!blockers.some((o) => boxesMeet(o, b))) return t;', replace: 'return t;', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/busvalues.ts', what: 'a bus chip on another wire\'s side',
    find: 'if (boxToWire(box, g) <= mine) return false;', replace: '', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/busvalues.ts', what: 'a bus chip\'s leader across another wire',
    find: 'if (segmentMeetsBox(anchor, mid, gb)) return false;', replace: '', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/logic.ts', what: 'a group border past the band (chips touch it)',
    find: 'bandWithin(inner + 4 / zoom, zoom)', replace: 'inner + 4 / zoom', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/influence.ts', what: 'the reached bus values left under the dimming',
    find: '    this.drawChips(d, nets);\n', replace: '', tests: ['tests/e2e/overlays.e2e.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/flow.ts', what: 'the arcs and labels of a finished flow not drawn',
    find: '      drawn.arcs.push(', replace: '      if (f < 2) return;\n      drawn.arcs.push(', tests: ['tests/e2e/overlays.e2e.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/busvalues.ts', what: 'a bus chip over a wire',
    find: "obs.add({ x0: Math.min(s.a[0], s.b[0]) - WIRE_GAP, y0: Math.min(s.a[1], s.b[1]) - WIRE_GAP, x1: Math.max(s.a[0], s.b[0]) + WIRE_GAP, y1: Math.max(s.a[1], s.b[1]) + WIRE_GAP }, `wire:${s.id}`);", replace: '', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/labels.ts', what: 'label chips on the bands around wires',
    find: ' && !bands.hits(b)) ??', replace: ') ??', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/scene.ts', what: 'groups and memos of a change not taken',
    find: '    if (c.groups || c.memos) this.setExt(c.groups ?? [...this.groups.values()], c.memos ?? this.memos);\n', replace: '', tests: ['tests/unit/overlays.test.ts'] },
  { module: 'overlays', file: 'src/main/recovery.ts', what: 'a signal group\'s wire journaled as an id',
    find: "componentId: 'one', wire: 'one' }", replace: "componentId: 'one' }", tests: ['tests/unit/recovery.test.ts'] },
  { module: 'overlays', file: 'src/renderer/canvas/overlays/controller.ts', what: 'Signal Flow on Click off at start',
    find: 'this.settings = { onClick: true,', replace: 'this.settings = { onClick: false,', tests: ['tests/e2e/overlays.e2e.ts'] },
  // ---- recovery files beside the student's files (N-19, D-152)
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'an older recovery file asked about',
    find: 'return r.mtimeMs >= c.mtimeMs ? { path: rec, modified: r.mtimeMs } : null;', replace: 'return { path: rec, modified: r.mtimeMs };',
    tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'a new file (no place) waits for a write',
    find: '    if (!this.hasPlace(fileId)) return;\n', replace: '', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'no write while edits keep coming (no longest wait)',
    find: 'Math.min(this.idleMs, w.first + this.maxWaitMs - now)', replace: 'this.idleMs', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'no write after so many edits',
    find: 'w.edits >= this.maxEdits ? 0 : ', replace: '', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'a save or a close does not drop the waiting write',
    find: "    else if (a.method === 'file.save' || a.method === 'file.close') this.forget(p.fileId);\n", replace: '',
    tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'a write while a crash recovery replays',
    find: '    await this.settled();\n', replace: '', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery-files.ts', what: 'the replay\'s own edits taken for the window\'s',
    find: 'if (a.tag === WINDOW && journaled(a.method))', replace: 'if (journaled(a.method))', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery.ts', what: 'a recovered file\'s journal not started over at a write',
    find: "      this.journal.rebased(p.fileId, this.shadow.circuitIds(p.fileId), this.fingerprint(r.path));\n", replace: '',
    tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery.ts', what: 'a recovered file opened again as saved after an engine crash',
    find: "...(recover ? { recovery: 'recover' } : {})", replace: '...{}', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/recovery.ts', what: 'the Supervisor\'s own close removes the recovery file',
    find: "{ fileId: f.fileId, keepRecovery: true }", replace: '{ fileId: f.fileId }', tests: ['tests/unit/recovery-files.test.ts'] },
  { module: 'recovery-files', file: 'src/main/main.ts', what: 'the engine not asked to keep recovery files (none written as the app dies)',
    find: 'helloParams: () => ({ recoveryFiles: true,', replace: 'helloParams: () => ({ recoveryFiles: false,', tests: ['tests/e2e/recovery-file.e2e.ts'] },
  { module: 'recovery-files', file: 'src/main/main.ts', what: 'a file with a recovery file opened without the question',
    find: 'const beside = recovery ? null : recoveryBeside(path.resolve(p));', replace: 'const beside = null;', tests: ['tests/e2e/recovery-file.e2e.ts'] },
  { module: 'recovery-files', file: 'src/renderer/app/logic/recovery-ask.ts', what: 'Esc taken for Discard',
    find: "c === 'cancel' ? 'discard' : null", replace: "'discard'", tests: ['tests/unit/recovery-ask.test.ts'] },
  { module: 'recovery-files', file: 'src/renderer/app/app.ts', what: 'recovered edits shown as saved',
    find: '    files.setDirty(r.fileId, true);\n', replace: '', tests: ['tests/e2e/recovery-file.e2e.ts'] },
  // ---- leaving with unsaved changes (N-19, D-152)
  { module: 'leaving', file: 'src/renderer/app/logic/unsaved.ts', what: 'Discard stops the quit',
    find: "    if (c === 'extra') continue;", replace: "    if (c === 'extra') return false;", tests: ['tests/unit/unsaved.test.ts'] },
  { module: 'leaving', file: 'src/renderer/app/logic/unsaved.ts', what: 'a save that did not happen lets the quit go on',
    find: "    if (c !== 'ok' || !(await o.save(f))) return false;", replace: "    if (c !== 'ok') return false;\n    await o.save(f);", tests: ['tests/unit/unsaved.test.ts'] },
  { module: 'leaving', file: 'src/main/main.ts', what: 'the close button closes without asking',
    find: "    if (leaveConfirmed || quitting || !windowListens || win.webContents.isCrashed()) return;", replace: '    return;', tests: ['tests/e2e/quit.e2e.ts'] },
  { module: 'leaving', file: 'src/main/main.ts', what: 'the PC shutting down not held back',
    find: "    if (!windowDirty || leaveConfirmed || !windowListens) return;", replace: '    return;', tests: ['tests/e2e/quit.e2e.ts'] },
  { module: 'leaving', file: 'src/renderer/app/app.ts', what: 'Ctrl+Q does nothing',
    find: "  else if (k === 'q') { e.preventDefault(); void leave(); }\n", replace: '', tests: ['tests/e2e/quit.e2e.ts'] },
  { module: 'leaving', file: 'src/renderer/app/app.ts', what: 'a tab closes without asking',
    find: "  if (!(await unsavedSettled([f], 'close'))) return;\n", replace: '', tests: ['tests/e2e/quit.e2e.ts'] },
  // ---- settings for this run only (N-19)
  { module: 'labpc', file: 'src/renderer/canvas/legend.ts', what: 'the settings panel does not say "for this run only"',
    find: "    h('p', { class: 'legend-note' }, RUN_ONLY));", replace: '  );', tests: ['tests/e2e/labpc.e2e.ts'] },
  { module: 'labpc', file: 'src/renderer/app/app.ts', what: 'a clock speed other than the default at the start',
    find: 'selected: hz === RUN_DEFAULTS.hz', replace: 'selected: hz === 64', tests: ['tests/e2e/labpc.e2e.ts'] },
  // ---- the simulation (N-07, D-145: logic/sim.ts, canvas/poke.ts, app/editor.ts)
  { module: 'sim', file: 'src/renderer/app/logic/sim.ts', what: 'Run stays Run while N Cycles goes (no way to stop it)',
    find: "!!s && (s.ticking || (s.cyclesLeft ?? 0) > 0)", replace: '!!s && s.ticking', tests: ['tests/unit/sim.test.ts'] },
  { module: 'sim', file: 'src/renderer/app/logic/sim.ts', what: 'Reset turns on what Ctrl+E turned off',
    find: '!!s && !s.running && s.oscillating;', replace: '!!s && !s.running;', tests: ['tests/unit/sim.test.ts'] },
  { module: 'sim', file: 'src/renderer/app/logic/sim.ts', what: 'N Cycles takes 0',
    find: 'if (n < CYCLES_MIN || n > CYCLES_MAX)', replace: 'if (n > CYCLES_MAX)', tests: ['tests/unit/sim.test.ts'] },
  { module: 'sim', file: 'src/renderer/canvas/poke.ts', what: 'the poked wire\'s decimal unsigned',
    find: "const s = v[0] === '1' ? u - (1n << BigInt(width)) : u;", replace: 'const s = u;', tests: ['tests/unit/canvas-poke.test.ts'] },
  { module: 'sim', file: 'src/renderer/canvas/poke.ts', what: 'the lens too wide (a double click anywhere in the box goes inside)',
    find: 'return dx * dx + dy * dy <= 60;', replace: 'return dx * dx + dy * dy <= 6000;', tests: ['tests/unit/canvas-poke.test.ts'] },
  { module: 'sim', file: 'src/renderer/canvas/poke.ts', what: 'keys with Ctrl go to a poked register',
    find: 'if (e.ctrlKey || e.altKey || e.metaKey || e.isComposing) return null;', replace: 'if (e.isComposing) return null;', tests: ['tests/unit/canvas-poke.test.ts'] },
  { module: 'sim', file: 'src/renderer/app/editor.ts', what: 'a poke sent as one click (the pin\'s press and release not apart)',
    find: "void this.send(p.where, p.id, e.at, 'release')", replace: 'void Promise.resolve(null)', tests: ['tests/e2e/sim.e2e.ts'] },
  { module: 'sim', file: 'src/renderer/app/app.ts', what: 'the band not shown while the simulation is off',
    find: '  if (text) simOffBand.show(text, \'error\');', replace: '  if (false) simOffBand.show(text!, \'error\');', tests: ['tests/e2e/sim.e2e.ts'] },
  // ---- performance (N-22, D-160: logic/sim.ts countOnly and its use, tools/perf-goals.ts)
  { module: 'perf', file: 'src/renderer/app/logic/sim.ts', what: 'Run becoming Stop taken as the count only (the button stays Run)',
    find: '&& before.hz === now.hz && going(before) === going(now);', replace: '&& before.hz === now.hz;', tests: ['tests/unit/sim.test.ts'] },
  { module: 'perf', file: 'src/renderer/app/logic/sim.ts', what: 'an oscillation taken as the count only (no band)',
    find: 'before.ticking === now.ticking && before.oscillating === now.oscillating', replace: 'before.ticking === now.ticking', tests: ['tests/unit/sim.test.ts'] },
  { module: 'perf', file: 'src/renderer/app/app.ts', what: 'every sim.state draws the whole window (Run at 4 kHz stutters)',
    find: 'if (countOnly(before, st)) renderStatus(); else render();', replace: 'render();', tests: ['tests/e2e/sim.e2e.ts'] },
  { module: 'perf', file: 'src/renderer/app/app.ts', what: 'Run becoming Stop draws the status bar only',
    find: 'if (countOnly(before, st)) renderStatus(); else render();', replace: 'renderStatus();', tests: ['tests/e2e/sim.e2e.ts'] },
  { module: 'perf', file: 'tools/perf-goals.ts', what: 'a dropped frame not counted',
    find: 'Math.max(0, Math.round(x / FRAME_MS) - 1)', replace: 'Math.max(0, Math.round(x / FRAME_MS) - 2)', tests: ['tests/unit/perf-goals.test.ts'] },
  { module: 'perf', file: 'tools/perf-goals.ts', what: 'over the CI limit only missed (CI never fails)',
    find: "return withinLimit ? { status: 'missed', note: 'over the goal, within the CI limit' } : { status: 'failed' };", replace: "return { status: 'missed', note: 'over the goal, within the CI limit' };", tests: ['tests/unit/perf-goals.test.ts'] },
  { module: 'perf', file: 'tools/perf-goals.ts', what: 'report-only everywhere',
    find: '  const only = REPORT_ONLY[r.where] ?? {};', replace: "  const only = REPORT_ONLY['windows'] ?? {};", tests: ['tests/unit/perf-goals.test.ts'] },
  { module: 'perf', file: 'tools/perf-goals.ts', what: 'the first start judged on a warm one',
    find: '  const first = r.firstAfterInstall ?? r.starts?.[0];', replace: '  const first = r.firstAfterInstall ?? r.starts?.at(-1);', tests: ['tests/unit/perf-goals.test.ts'] },
  { module: 'perf', file: 'tools/perf-goals.ts', what: 'a missing measurement counted as met',
    find: "  return { id, what, value: '—', goal, status: 'skipped', note: r.skipped?.[key] ?? 'not measured' };", replace: "  return { id, what, value: '—', goal, status: 'met' };", tests: ['tests/unit/perf-goals.test.ts'] },
  // ---- editing (N-08, D-146: canvas/gestures.ts, app/logic/editing.ts, app/edit-tools.ts, app/editor.ts)
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'a half rounds down on the grid',
    find: 'Math.floor((v + 5) / GRID) * GRID', replace: 'Math.floor((v + 4) / GRID) * GRID', tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'a wiring point however far from the grid',
    find: 'if (!(dx * dx + dy * dy < 36 || alt)) return null;', replace: 'if (!(dx * dx + dy * dy < 3600 || alt)) return null;', tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'Alt does not turn the wiring point round',
    find: 'const wiring = !alt, select = alt;', replace: 'const wiring = true, select = false;', tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'a selected wire\'s middle draws a wire instead of dragging it',
    find: 'if (selected.has(w.id) && wireContains(w, snap) && !wireEndsAt(w, snap)) return select;', replace: '', tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'the L\'s bend never decided again',
    find: "    } else if (this.direction === 'h' && n[0] === s[0]) {", replace: "    } else if (false) {", tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'an L bends at the wrong corner',
    find: "const m: Point = this.direction === 'h' ? [c[0], s[1]] : [s[0], c[1]];", replace: "const m: Point = this.direction === 'h' ? [s[0], c[1]] : [c[0], s[1]];", tests: ['tests/unit/gestures.test.ts', 'tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'a click is any press and release',
    find: 'return dx * dx + dy * dy <= 4;', replace: 'return true;', tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/gestures.ts', what: 'a drag above the page\'s top',
    find: 'if (bounds) { x = Math.max(x, -bounds.x0); y = Math.max(y, -bounds.y0); }', replace: '', tests: ['tests/unit/gestures.test.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/editing.ts', what: 'Backspace with nothing selected is not the wire\'s undo',
    find: "return e.key === 'Backspace' && !e.altKey && !e.shiftKey ? { kind: 'undoWire' } : null;", replace: 'return null;', tests: ['tests/unit/editing.test.ts', 'tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/editing.ts', what: 'Shift+R turns clockwise too',
    find: "return { kind: 'rotate', clockwise: !e.shiftKey };", replace: "return { kind: 'rotate', clockwise: true };", tests: ['tests/unit/editing.test.ts', 'tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/editing.ts', what: 'digits read by the key\'s letter (a Korean layout, Alt)',
    find: "const m = /^(?:Digit|Numpad)([0-9])$/.exec(code);", replace: "const m = /^(?:Numpad)([0-9])$/.exec(code);", tests: ['tests/unit/editing.test.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/editing.ts', what: 'digits never make one number',
    find: 'export const chained = (last: number, now: number): boolean => now - last < CHAIN_MS;', replace: 'export const chained = (_last: number, _now: number): boolean => false;', tests: ['tests/unit/editing.test.ts', 'tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/editing.ts', what: 'an output pin poked by Ctrl+click',
    find: "export const isInputPin = (c: Component): boolean => c.lib === 'Wiring' && c.name === 'Pin' && c.attrs.output !== 'true';", replace: "export const isInputPin = (c: Component): boolean => c.lib === 'Wiring' && c.name === 'Pin';", tests: ['tests/unit/editing.test.ts'] },
  { module: 'edit', file: 'src/renderer/app/edit-tools.ts', what: 'Shift while dragging keeps the wires following',
    find: "void this.host.edit('edit.move', { fileId: w.fileId, circuitId: w.circuitId, dx: pr.dx, dy: pr.dy, connect: !e.shift }, 'Move');", replace: "void this.host.edit('edit.move', { fileId: w.fileId, circuitId: w.circuitId, dx: pr.dx, dy: pr.dy, connect: true }, 'Move');", tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/edit-tools.ts', what: 'a rectangle with Shift replaces the selection',
    find: "rect: [b.x0, b.y0, b.x1, b.y1], add: pr.shift }", replace: "rect: [b.x0, b.y0, b.x1, b.y1], add: false }", tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/edit-tools.ts', what: 'a wire from the Edit tool takes the Wiring tool (the selection goes)',
    find: "points: pr.drag.points(), tool: 'edit' }", replace: "points: pr.drag.points(), tool: 'wiring' }", tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/edit-tools.ts', what: 'the placing tool\'s ghost off the grid',
    find: '    this.at = snapPoint(logical(e.at));\n    this.draw();', replace: '    this.at = logical(e.at);\n    this.draw();', tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/edit-tools.ts', what: 'Esc applies a text',
    find: "if (e.key === 'Escape') { e.preventDefault(); this.cancel(); }", replace: "if (e.key === 'Escape') { e.preventDefault(); void this.commit(); }", tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/edit-tools.ts', what: 'a double click on an input pin edits its label',
    find: 'if (isInputPin(c)) { this.host.pinValue(c); return; }', replace: '', tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/editor.ts', what: 'Paste keeps the tool in hand',
    find: "case 'paste': this.setTool('Edit'); call('edit.paste', 'Paste'); break;", replace: "case 'paste': call('edit.paste', 'Paste'); break;", tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/editor.ts', what: 'the same selection told again and again',
    find: '    if (k === this.told) return;\n', replace: '', tests: ['tests/e2e/tool-events.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/canvas/canvas.ts', what: 'the pointer over the Canvas takes the keys from a field being typed in',
    find: "if (!typing && !document.querySelector('dialog[open]')) c.focus({ preventScroll: true });", replace: 'c.focus({ preventScroll: true });', tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/engine-status.ts', what: 'the first status answer undoes a newer push',
    find: '    if (this.pushes === before) this.status = s;', replace: '    this.status = s;', tests: ['tests/unit/engine-status.test.ts'] },
  { module: 'edit', file: 'src/renderer/app/logic/selection-facts.ts', what: 'one part told as a count',
    find: '  if (parts.length === 1 && wires === 0) {', replace: '  if (false) {', tests: ['tests/unit/selection-facts.test.ts', 'tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'src/renderer/app/app.ts', what: 'the Attributes panel forgets a paste not yet placed',
    find: '  if (f && s) chosen.push(...(editor.selection()?.floating ?? []));', replace: '', tests: ['tests/e2e/edit.e2e.ts'] },
  { module: 'edit', file: 'tests/fake-engine/fake-engine.ts', what: 'the fake\'s empty Delete is no undo step',
    find: "if (!ids.size) { f.undo.push(copyParts(c)); f.redo = []; f.dirty = true; return { changed: true, outcome: 'empty' }; }", replace: "if (!ids.size) return { changed: false, outcome: 'empty' };", tests: ['tests/unit/recovery.test.ts'] },
  // ---- circuits, appearances, libraries, windows (N-11, D-153)
  { module: 'circuits', file: 'src/renderer/app/logic/circuits.ts', what: 'renaming a circuit to its own name refused',
    find: 'c.name === n && c.circuitId !== self', replace: 'c.name === n', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/circuits.ts', what: 'every place of an impact listed',
    find: 'export const IMPACT_PLACES = 8;', replace: 'export const IMPACT_PLACES = 80;', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/circuits.ts', what: 'same names told apart by the whole folder path',
    find: '        if (!clash) break;\n', replace: '', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/circuits.ts', what: 'a port moved goes to the end of its side',
    find: '  out.splice(to, 0, x);', replace: '  out.push(x);', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/appearance.ts', what: 'a polygon never closes on its first point',
    find: 'return Math.abs(a[0] - b[0]) + Math.abs(a[1] - b[1]) <= CLOSE_TOLERANCE;', replace: 'return false;', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/appearance.ts', what: 'a line\'s end snapped to the grid before 45°',
    find: '  const e: P = m.shift ? snap8(start, end) : end;\n  return m.ctrl ? [snap(e[0]), snap(e[1])] : e;',
    replace: '  const g: P = m.ctrl ? [snap(end[0]), snap(end[1])] : end;\n  return m.shift ? snap8(start, g) : g;', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/appearance.ts', what: 'presses never count on (a polyline never ends on a double click)',
    find: 'return { t, x, y, n: on ? last.n + 1 : 1 };', replace: 'return { t, x, y, n: 1 };', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/appearance-editor.ts', what: 'a polygon\'s last corner follows the pointer without a press (PolyTool has no mouseMoved)',
    find: "        if (!down) return;   // PolyTool: mouseDragged only (no mouseMoved) -- the last corner follows a drag, not a hover\n", replace: '',
    tests: ['tests/e2e/circuits-editing.e2e.ts'] },
  { module: 'circuits', file: 'src/renderer/app/appearance-editor.ts', what: 'the text field loses the focus to the press that made it',
    find: "    setTimeout(() => { if (this.textField === field) field.focus(); }, 0);\n", replace: '', tests: ['tests/e2e/circuits-editing.e2e.ts'] },
  { module: 'circuits', file: 'src/main/windows.ts', what: 'a window of its own starts from its handover again and again',
    find: '    this.handovers.delete(webContentsId);\n', replace: '', tests: ['tests/unit/windows.test.ts'] },
  { module: 'circuits', file: 'src/main/windows.ts', what: 'every notification to the main window',
    find: "    return this.ownerOf(typeof fileId === 'string' ? fileId : null);", replace: '    return this.ownerOf(null);', tests: ['tests/unit/windows.test.ts'] },
  { module: 'circuits', file: 'src/main/recovery.ts', what: 'the recovery shadow keeps a removed circuit',
    find: '      for (const id of [...(f?.keys() ?? [])]) if (!now.has(id)) f!.delete(id);\n', replace: '', tests: ['tests/unit/windows.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/app.ts', what: 'a save breaks the connections of other files without asking',
    find: '  if (!saveAs && !(await circuitCtl.saveCuts(f))) return;\n', replace: '', tests: ['tests/e2e/circuits-editing.e2e.ts'] },
  { module: 'circuits', file: 'src/main/main.ts', what: 'the main window closes before the windows of their own asked about their files',
    find: '    if (!quitting && windows.detached().length > 0) {', replace: '    if (false) {', tests: ['tests/e2e/circuits-editing.e2e.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/circuits.ts', what: 'the Simulation Tree in the file\'s order, not by name',
    find: "      .sort((a, b) => a.text.toLowerCase().localeCompare(b.text.toLowerCase()) || place(a.p).localeCompare(place(b.p)));\n", replace: '', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/circuits.ts', what: 'the Simulation Tree enters a circuit already on the path',
    find: '      if (seen.includes(p.subcircuit)) continue;\n', replace: '', tests: ['tests/unit/circuits-logic.test.ts'] },
  { module: 'circuits', file: 'src/main/circuit-files.ts', what: 'a drop opens any file',
    find: "if (typeof p !== 'string' || !/\\.circ$/i.test(p) || !path.isAbsolute(p)) continue;", replace: "if (typeof p !== 'string' || !path.isAbsolute(p)) continue;", tests: ['tests/unit/windows.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/app.ts', what: 'the dropped files handed over as a FileList (empty across the bridge)',
    find: 'await api.openDropped([...list])', replace: 'await api.openDropped(list as unknown as File[])', tests: ['tests/e2e/circuits-editing.e2e.ts'] },
  { module: 'circuits', file: 'src/main/recovery.ts', what: 'a library saved in another file not journaled (a replay loses it)',
    find: "        this.journal.record(params.fileId, 'edit.reloadLibrary', { fileId: params.fileId, lib: params.lib }, this.shadow);\n", replace: '',
    tests: ['tests/unit/recovery.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/app.ts', what: 'same names told apart only among this window\'s files',
    find: "  for (const x of everyFile) if (x.path) byId.set(", replace: "  for (const x of [] as typeof everyFile) if (x.path) byId.set(",
    tests: ['tests/e2e/circuits.e2e.ts'] },
  { module: 'circuits', file: 'src/renderer/app/logic/search.ts', what: 'the search box\'s example text cut in a narrow panel',
    find: "  return SEARCH_HINTS.find((t) => measure(t) <= room) ?? SEARCH_HINTS[SEARCH_HINTS.length - 1];", replace: "  return SEARCH_HINTS[0];",
    tests: ['tests/unit/search.test.ts'] },
  { module: 'circuits', file: 'src/renderer/app/circuits.ts', what: 'the row a menu is open on not marked',
    find: "    row.classList.add('menuon');\n", replace: '', tests: ['tests/e2e/circuits.e2e.ts'] },
  { module: 'circuits', file: 'src/renderer/app/circuit-control.ts', what: 'Port Order applied without the question',
    find: "const r = await this.call<Result>(method, { ...params, confirm: false }, name);", replace: "const r = await this.call<Result>(method, { ...params, confirm: true }, name);",
    tests: ['tests/e2e/circuits.e2e.ts'] },
  // ---- the Attributes panel, Quick Attributes and the right-click menus (N-10, D-157)
  { module: 'attributes', file: 'src/renderer/app/logic/menu-layout.ts', what: 'the common group before the part\'s own items',
    find: '  for (const s of specific) group(s);\n  if (common.length) group(common);', replace: '  if (common.length) group(common);\n  for (const s of specific) group(s);', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/logic/menu-layout.ts', what: 'Delete not last',
    find: "      else if (group === 'delete') del.push(e);", replace: "      else if (group === 'delete') common.push(e);", tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/registry.ts', what: 'providers not in their order',
    find: '  list.sort((a, b) => a.order - b.order);', replace: '', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/canvas-items.ts', what: 'Negate Input sets what it was',
    find: 'run: () => set(t, one, q.negate!, String(!q.negated)) });', replace: 'run: () => set(t, one, q.negate!, String(q.negated)) });', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/canvas-items.ts', what: 'a Constant offered on an output',
    find: "kinds.filter(([k]) => k !== 'constant' || q.dir !== 'out')", replace: 'kinds', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/canvas-items.ts', what: 'wires combined in an order nobody chose',
    find: 'disabled: !ed || !f.selection.ordered || !known,', replace: 'disabled: !ed || !known,', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/canvas-items.ts', what: 'Attach Probe with several chosen',
    find: "if (f.kind === 'wire' && f.id && f.selection.ids.length <= 1) {", replace: "if (f.kind === 'wire' && f.id) {", tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/canvas-items.ts', what: 'a menu item on one part changes the selection',
    find: "...(keep ? { keepSelection: true } : {})", replace: '', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/logic/attributes.ts', what: 'Quick Attributes shows a read-only attribute',
    find: "    if (!row || row.readOnly || row.type === 'contents') continue;", replace: "    if (!row || row.type === 'contents') continue;", tests: ['tests/unit/attributes.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/logic/attributes.ts', what: 'the bar covers a part as soon as a wire',
    find: 'export const HARD_WEIGHT = 1000;', replace: 'export const HARD_WEIGHT = 1;', tests: ['tests/unit/attributes.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/logic/attributes.ts', what: 'two circuits of one name',
    find: "  if (others.includes(n)) return '같은 이름의 회로가 이미 있습니다. 다른 이름을 적으세요.';\n", replace: '', tests: ['tests/unit/attributes.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/logic/attributes.ts', what: 'the Text tool\'s table is the selection\'s',
    find: "  if (tool === 'Text') return { kind: 'tool', fileId, lib: 'Base', name: 'Text Tool' };\n", replace: '', tests: ['tests/unit/attributes.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/attributes.ts', what: 'a refused value said nowhere',
    find: '        this.fail(r, badValueSentence(r, value), value);', replace: '        this.host.failed(r.display, e);', tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/attributes.ts', what: 'the circuit\'s attributes sent to the selection',
    find: "t.target === 'circuit' ? 'edit.setCircuitAttr' : 'edit.setAttr'", replace: "'edit.setAttr'", tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/quick-attributes.ts', what: 'the bar back while the button is still down',
    find: '    if (this.pressed || this.quiet ||', replace: '    if (this.quiet ||', tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/quick-attributes.ts', what: 'the bar back right after a drag (S-04)',
    find: '      if (at && at.onPart && Math.hypot(e.clientX - at.x, e.clientY - at.y) > 3) this.quiet = true;', replace: '', tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/canvas-menu.ts', what: 'the P key picks the radix itself (the engine\'s rule: 1 bit binary)',
    find: "void d.call<EditResult>('edit.probe', { fileId: w.fileId, circuitId: w.circuitId, wire, at })", replace: "void d.call<EditResult>('edit.probe', { fileId: w.fileId, circuitId: w.circuitId, wire, at, radix: '16' })",
    tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/dialogs.ts', what: 'Duplicate N… takes any count',
    find: "      if (!Number.isInteger(n) || n < 1 || n > 64) return { error: '복제할 수는 1–64 사이의 정수입니다.' };\n", replace: '', tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/dialogs.ts', what: 'a copy\'s label loses its leading zeros',
    find: '.padStart(m[2].length, \'0\')', replace: '', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/hex-editor.ts', what: 'the caret goes down one word, not one row',
    find: "    case 'ArrowDown': return clamp(at + COLS);", replace: "    case 'ArrowDown': return clamp(at + 1);", tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/renderer/app/hex-editor.ts', what: 'a RAM\'s word written as the file\'s (an undo step)',
    find: "        if (t.kind === 'ram') await host.call('mem.write', { ...base, addr, values });", replace: "        if (t.kind === 'nothing') await host.call('mem.write', { ...base, addr, values });", tests: ['tests/e2e/attributes.e2e.ts'] },
  { module: 'attributes', file: 'src/renderer/app/menus/side-menus.ts', what: 'a Components entry\'s library read wrong',
    find: '  const lib = key.slice(0, i);', replace: '  const lib = key.slice(0, i + 1);', tests: ['tests/unit/menus.test.ts'] },
  { module: 'attributes', file: 'src/main/recovery.ts', what: 'the journal writes the right-click menu\'s parts down by id',
    find: "export const ID_PARAMS: Readonly<Record<string, 'list' | 'one'>> = { ids: 'list', id: 'one', componentId: 'one', wire: 'one' };",
    replace: "export const ID_PARAMS: Readonly<Record<string, 'list' | 'one'>> = { id: 'one', componentId: 'one', wire: 'one' };", tests: ['tests/unit/recovery.test.ts'] },
];

function copyTree(dir: string): void {
  for (const d of ['src', 'tests', 'tools', 'packaging']) cpSync(path.join(root, d), path.join(dir, d), { recursive: true });
  for (const f of ['package.json', 'tsconfig.json', 'playwright.config.ts', 'ORIGIN.md', 'LICENSE.hallym-mips.txt', 'hallym-assets.md']) cpSync(path.join(root, f), path.join(dir, f));
  symlinkSync(path.join(root, 'node_modules'), path.join(dir, 'node_modules'));
  // The repository around electron/: its notices, the marks and characters, the test circuits.
  for (const f of ['LICENSE', 'NOTICE']) cpSync(path.join(root, '..', f), path.join(dir, '..', f));
  // engine/: its build file names the runtime's OpenJDK release (tests/unit/notice.test.ts).
  for (const d of ['assets', 'tests', 'engine']) symlinkSync(path.join(root, '..', d), path.join(dir, '..', d));
}

if (import.meta.main) {
  const filter = process.argv[2] ?? '';
  const selected = MUTANTS.filter((m) => `${m.module} ${m.what}`.includes(filter));
  let bad = 0;
  const rows: string[] = [];
  for (const m of selected) {
    const outer = mkdtempSync(path.join(os.tmpdir(), 'mutant-'));
    const dir = path.join(outer, 'electron');
    mkdirSync(dir);
    try {
      copyTree(dir);
      const file = path.join(dir, m.file);
      const text = readFileSync(file, 'utf8');
      const count = text.split(m.find).length - 1;
      if (count !== 1) {
        rows.push(`NOT APPLIED  ${m.module}: ${m.what} (found ${count} times)`);
        bad += 1;
        continue;
      }
      writeFileSync(file, text.replace(m.find, m.replace));
      const e2e = m.tests.every((t) => t.endsWith('.e2e.ts'));
      if (e2e) execFileSync(process.execPath, ['tools/build-ui.ts'], { cwd: dir, stdio: 'ignore' });
      const run = e2e
        ? spawnSync(process.execPath, [path.join(root, 'node_modules/@playwright/test/cli.js'), 'test', ...m.tests],
                    { cwd: dir, encoding: 'utf8', timeout: 300000 })
        : spawnSync(process.execPath, ['--test', '--test-reporter=tap', ...m.tests], { cwd: dir, encoding: 'utf8', timeout: 300000 });
      const firstFailure = (e2e ? /^\s*\d+\) (.*)$/m.exec(run.stdout)?.[1]?.replace(/─+$/, '').trim()
                                : /^\s*not ok \d+ - (.*)$/m.exec(run.stdout)?.[1]) ?? '(no test reported a failure)';
      if (run.status === 0) {
        rows.push(`SURVIVED     ${m.module}: ${m.what}`);
        bad += 1;
      } else {
        rows.push(`killed       ${m.module}: ${m.what}  <-  ${firstFailure}`);
      }
    } finally {
      rmSync(outer, { recursive: true, force: true });
    }
  }
  console.log(rows.join('\n'));
  console.log(`\n${selected.length - bad} of ${selected.length} mutants killed`);
  process.exit(bad === 0 ? 0 : 1);
}
