/*
 * Hallym Circuit Studio
 * Copyright (c) 2026 AIAC Lab, Hallym University.
 * License: GNU GPL version 2 or later. See LICENSE.
 */
package kr.ac.hallym.hcs.engine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import com.cburch.logisim.comp.ComponentFactory;
import com.cburch.logisim.data.Attribute;
import com.cburch.logisim.std.Builtin;
import com.cburch.logisim.tools.AddTool;
import com.cburch.logisim.tools.Library;
import com.cburch.logisim.tools.Tool;

import kr.ac.hallym.hcs.app.palette.Palette;

/**
 * 검색 창·부품 목록 검색의 뒤 숫자(N-12, D-150, v1 {@link Palette#attributesFor}): {@code and 3}은 입력 수,
 * {@code mux 32}는 폭. 화면은 엔진에 도구 속성을 묻지 않는다(엔진이 도구의 속성 묶음을 만들면 저장에 {@code <tool>}이
 * 붙는다, D-149). 그래서 화면의 표 {@code electron/src/renderer/app/logic/tool-args.ts}를 여기서 v1 규칙으로 만들고
 * 저장소의 것과 같은지 본다. 다시 쓰기: {@code ./gradlew :engine:test --tests '*ToolArgsTest' -Phcs.update=true}.
 * <p>
 * 도구는 이 테스트만의 새 라이브러리에서 부른다(내장 라이브러리는 새 {@link Builtin}, Hallym MIPS는 따로 된 클래스
 * 로더): 엔진과 다른 테스트가 쓰는 도구 객체의 속성 묶음을 만들지 않는다.
 */
class ToolArgsTest {
    static final File TABLE = new File(new File(System.getProperty("hcs.electronFixtures")).getParentFile().getParentFile(),
            "src/renderer/app/logic/tool-args.ts");
    static final String MIPS = "kr.ac.hallym.hcs.mips.MipsLibrary";

    @Test
    void theScreensTableIsV1sRuleForEveryTool() throws Exception {
        String want = table();
        if (Boolean.getBoolean("hcs.update") || "true".equals(System.getProperty("hcs.update"))) {
            Files.write(TABLE.toPath(), want.getBytes(StandardCharsets.UTF_8));
        }
        assertTrue(TABLE.isFile(), "missing " + TABLE + ": run with -Phcs.update=true");
        assertEquals(want, new String(Files.readAllBytes(TABLE.toPath()), StandardCharsets.UTF_8),
                "tool-args.ts is not what the engine's tools say: ./gradlew :engine:test --tests '*ToolArgsTest' -Phcs.update=true");
    }

    static String table() throws Exception {
        List<Library> libs = new ArrayList<>(new Builtin().getLibraries());
        try (URLClassLoader cl = new URLClassLoader(new URL[] {new File(System.getProperty("hcs.bundledMips")).toURI().toURL()},
                ToolArgsTest.class.getClassLoader())) {
            libs.add((Library) cl.loadClass(MIPS).getDeclaredConstructor().newInstance());
            StringBuilder sb = new StringBuilder();
            sb.append("/* Generated by engine/src/test/java/kr/ac/hallym/hcs/engine/ToolArgsTest.java -- do not edit.\n")
                    .append("   What the number after a name sets (the search palette, the Components search;\n")
                    .append("   v1 Palette.attributesFor, D-150): a gate's number of inputs, a splitter's incoming\n")
                    .append("   width, a constant's value after 0x, else the width.  Key: library/tool as\n")
                    .append("   model.library names them.  A tool not here takes no number (it is listed as it is).\n")
                    .append("   The engine's test checks this file against the tools' own attributes. */\n\n")
                    .append("export interface ToolArg {\n")
                    .append("  attr: string;        // the .circ attribute the number sets\n")
                    .append("  label: string;       // its name in the attribute table (English)\n")
                    .append("  min: number;         // the numbers the original accepts\n")
                    .append("  max: number;\n")
                    .append("  hex?: string;        // after 0x: this attribute, the text as typed (a constant's value)\n")
                    .append("}\n\n")
                    .append("export const TOOL_ARGS: Readonly<Record<string, ToolArg>> = {\n");
            for (Library lib : libs) {
                String libName = lib.getClass().getName().equals(MIPS) ? MIPS : lib.getName();
                for (Tool t : lib.getTools()) {
                    if (!(t instanceof AddTool)) {
                        continue;
                    }
                    ComponentFactory f = ((AddTool) t).getFactory();
                    Map<String, String> probe = Palette.attributesFor(f, "4");
                    if (probe == null || probe.isEmpty()) {
                        probe = Palette.attributesFor(f, "2");
                    }
                    if (probe == null || probe.isEmpty()) {
                        continue;
                    }
                    String attr = probe.keySet().iterator().next();
                    int min = Integer.MAX_VALUE;
                    int max = Integer.MIN_VALUE;
                    for (int n = 0; n <= 64; n++) {
                        Map<String, String> m = Palette.attributesFor(f, Integer.toString(n));
                        if (m != null && m.containsKey(attr)) {
                            if (max != Integer.MIN_VALUE && n != max + 1) {
                                throw new AssertionError(t.getName() + ": the numbers are not one range");
                            }
                            min = Math.min(min, n);
                            max = n;
                        }
                    }
                    Attribute<?> a = f.createAttributeSet().getAttribute(attr);
                    sb.append("  '").append(libName).append('/').append(t.getName()).append("': { attr: '").append(attr)
                            .append("', label: '").append(a.getDisplayName()).append("', min: ").append(min)
                            .append(", max: ").append(max);
                    Map<String, String> hex = Palette.attributesFor(f, "0x1f");
                    if (hex != null && !hex.isEmpty() && !hex.containsKey(attr)) {
                        sb.append(", hex: '").append(hex.keySet().iterator().next()).append('\'');
                    }
                    sb.append(" },\n");
                }
            }
            sb.append("};\n");
            return sb.toString();
        }
    }
}
