#
# gui/Analyzer.java
#
analyzerWindowTitle = \uc870\ud569 \ud68c\ub85c \ubd84\uc11d
inputsTab = \uc785\ub825
outputsTab = \ucd9c\ub825
tableTab = \ud45c
expressionTab = \uc2dd
minimizedTab = \ucd5c\uc18c\ud654
inputsTabTip = \uc785\ub825 \ubcc0\uc218 \ubaa9\ub85d\uc744 \ubcf4\uace0 \ud3b8\uc9d1\ud569\ub2c8\ub2e4.
outputsTabTip = \ucd9c\ub825 \ubcc0\uc218 \ubaa9\ub85d\uc744 \ubcf4\uace0 \ud3b8\uc9d1\ud569\ub2c8\ub2e4.
tableTabTip = \uc9c4\ub9ac\ud45c\ub97c \ubcf4\uace0 \ud3b8\uc9d1\ud569\ub2c8\ub2e4.
expressionTabTip = \ucd9c\ub825\uc758 \uc2dd\uc744 \ubcf4\uace0 \ud3b8\uc9d1\ud569\ub2c8\ub2e4.
minimizedTabTip = \uc9c4\ub9ac\ud45c\uc5d0 \ub9de\ub294 \ucd5c\uc18c\ud654\ub41c \uc2dd\uc744 \ubd05\ub2c8\ub2e4.
#
# gui/BuildCircuitButton.java
#
buildCircuitButton = \ud68c\ub85c \ub9cc\ub4e4\uae30
buildProjectLabel = \ub300\uc0c1 \ud504\ub85c\uc81d\ud2b8:
buildNameLabel = \ud68c\ub85c \uc774\ub984:
buildTwoInputsLabel = 2\uc785\ub825 \uac8c\uc774\ud2b8\ub9cc \uc0ac\uc6a9
buildNandsLabel = NAND \uac8c\uc774\ud2b8\ub9cc \uc0ac\uc6a9
buildDialogTitle = \ud68c\ub85c \ub9cc\ub4e4\uae30
buildDialogErrorTitle = \ud68c\ub85c\ub97c \ub9cc\ub4e4 \uc218 \uc5c6\uc74c
buildNeedProjectError = \ub300\uc0c1 \ud504\ub85c\uc81d\ud2b8\ub97c \uc120\ud0dd\ud574\uc57c \ud569\ub2c8\ub2e4.
buildNeedCircuitError = \ud68c\ub85c \uc774\ub984\uc744 \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4.
buildConfirmReplaceMessage = %s \ud68c\ub85c\ub97c \ubc14\uafb8\uc2dc\uaca0\uc2b5\ub2c8\uae4c?
buildConfirmReplaceTitle = \ubc14\uafb8\uae30 \ud655\uc778
replaceCircuitAction = \ud68c\ub85c \ubc14\uafb8\uae30
#
# gui/ExpressionEditorPanel.java
#
exprClearButton = \uc9c0\uc6b0\uae30
exprRevertButton = \uc6d0\ub798\ub300\ub85c
exprEnterButton = \uc801\uc6a9
#
# gui/ExpressionPanel.java
#
expressionEmpty = (\ube44\uc5b4 \uc788\uc74c)
#
# gui/KarnaughMapPanel.java
#
karnaughNoOutputError = \uc120\ud0dd\ud55c \ucd9c\ub825\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.
karnaughTooManyInputsError = \uc785\ub825\uc774 \ub108\ubb34 \ub9ce\uc544 \ud45c\ub85c \ub098\ud0c0\ub0bc \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
#
# gui/MinimizedTabPanel.java
#
minimizedFormat = \ud615\uc2dd:
minimizedSumOfProducts = \uacf1\uc758 \ud569
minimizedProductOfSums = \ud569\uc758 \uacf1
minimizedSetButton = \uc2dd\uc73c\ub85c \uc124\uc815
#
# gui/OutputSelector.java
#
outputSelectLabel = \ucd9c\ub825:
#
# gui/SimpleTruthTablePanel.java
#
tableEmptyMessage = (\ube48 \ud45c)
tableNullHeader = (\uc5c6\uc74c)
#
# gui/TableTabClip.java
#
clipPasteErrorTitle = \ubd99\uc5ec\ub123\uae30 \uc624\ub958
clipPasteSupportedError = \ud074\ub9bd\ubcf4\ub4dc \ub0b4\uc6a9\uc744 \ud3b8\uc9d1\uae30\uc5d0 \ubd99\uc5ec\ub123\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
clipPasteEndError = \ud074\ub9bd\ubcf4\ub4dc \ub0b4\uc6a9\uc774 \ud45c\uc758 \ub05d\uc744 \ub118\uc5b4\uac11\ub2c8\ub2e4.
clipPasteSizeError = \ubd99\uc5ec\ub123\uc744 \uc601\uc5ed\uc758 \ud06c\uae30\uac00 \ud074\ub9bd\ubcf4\ub4dc \ub0b4\uc6a9\uacfc \uac19\uc544\uc57c \ud569\ub2c8\ub2e4.
#
# gui/VariableListPanel.java
#
variableRemoveButton = \uc81c\uac70
variableMoveUpButton = \uc704\ub85c
variableMoveDownButton = \uc544\ub798\ub85c
variableAddButton = \ucd94\uac00
variableRenameButton = \uc774\ub984 \ubc14\uafb8\uae30
variableStartError = \uc774\ub984\uc740 \uae00\uc790\ub85c \uc2dc\uc791\ud574\uc57c \ud569\ub2c8\ub2e4.
variablePartError = \uc774\ub984\uc5d0 '%s'\uc744(\ub97c) \uc4f8 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
variableDuplicateError = \uac19\uc740 \uc774\ub984\uc758 \ubcc0\uc218\uac00 \uc774\ubbf8 \uc788\uc2b5\ub2c8\ub2e4.
variableMaximumError = (\ucd5c\ub300 \uac1c\uc218 %s\uac1c\uc5d0 \uc774\ub974\ub800\uc2b5\ub2c8\ub2e4.)
#
# model/Entry.java
#
busError = \ud68c\ub85c\uc5d0\uc11c \ucd9c\ub825 \uac12\uc774 \ucda9\ub3cc\ud569\ub2c8\ub2e4.
oscillateError = \ud68c\ub85c\uac00 \ubc1c\uc9c4\ud569\ub2c8\ub2e4.
#
# model/Parser.java
#
implicitAndOperator = (\uc0dd\ub7b5\ub41c AND)
invalidCharacterError = \uc54c \uc218 \uc5c6\ub294 \ubb38\uc790: %s
missingLeftOperandError = \uc5f0\uc0b0\uc790 %s\uc758 \uc67c\ucabd \ud53c\uc5f0\uc0b0\uc790\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.
missingRightOperandError = \uc5f0\uc0b0\uc790 %s\uc758 \uc624\ub978\ucabd \ud53c\uc5f0\uc0b0\uc790\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.
lparenMissingError = \uc9dd\uc774 \ub9de\ub294 \uc5ec\ub294 \uad04\ud638\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.
rparenMissingError = \uc9dd\uc774 \ub9de\ub294 \ub2eb\ub294 \uad04\ud638\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.
badVariableName = %s\uc740(\ub294) \uc785\ub825 \ubcc0\uc218\uac00 \uc544\ub2d9\ub2c8\ub2e4.
unexpectedApostrophe = \uc608\uc0c1\ud558\uc9c0 \ubabb\ud55c \uc791\uc740\ub530\uc634\ud45c("'")
