#
# Analyze.java
#
defaultInputLabels = a,b,c,d,e,f,g,h
defaultOutputLabels = x,y,z,u,v,w,s,t
#
# AnalyzeException.java
#
analyzeCircularError = \uc21c\ud658 \ucc38\uc870\uac00 \uc788\uc5b4 \uc9c4\ub9ac\ud45c\ub97c \ub300\uc2e0 \uacc4\uc0b0\ud569\ub2c8\ub2e4.
analyzeConflictError = \ucd9c\ub825 \ucda9\ub3cc\uc774 \uc788\uc5b4 \uc9c4\ub9ac\ud45c\ub97c \ub300\uc2e0 \uacc4\uc0b0\ud569\ub2c8\ub2e4.
analyzeCannotHandleError = %s \ub54c\ubb38\uc5d0 \uc2dd \ub300\uc2e0 \uc9c4\ub9ac\ud45c\ub97c \uacc4\uc0b0\ud569\ub2c8\ub2e4.
#
# circuit/Circuit.java
#
circuitName = \ud68c\ub85c \uc774\ub984
circuitLabelLocAttr = \ub77c\ubca8 \uc704\uce58
circuitLabelAttr = \uacf5\uc6a9 \ub77c\ubca8
circuitLabelDirAttr = \uacf5\uc6a9 \ub77c\ubca8 \ubc29\ud5a5
circuitLabelFontAttr = \uacf5\uc6a9 \ub77c\ubca8 \uae00\uaf34
#
# circuit/CircuitMutation.java
#
unknownChangeAction = \ud68c\ub85c \ubc14\uafb8\uae30
#
# circuit/Subcircuit.java
#
subcircuitViewItem = %s \ubcf4\uae30
subcircuitCircuitTip = %s \ud558\uc704 \ud68c\ub85c
#
# circuit/RadixOption.java
#
radixAttr = \uc9c4\ubc95
radix2 = 2\uc9c4
radix10Signed = \ubd80\ud638 \uc788\ub294 10\uc9c4
radix10Unsigned = \ubd80\ud638 \uc5c6\ub294 10\uc9c4
radix8 = 8\uc9c4
radix16 = 16\uc9c4
#
# circuit/SplitterClass.java
#
# splitter component name
splitterComponent = \uc2a4\ud50c\ub9ac\ud130
# splitter end tool tips
splitterCombinedTip = \uc2a4\ud50c\ub9ac\ud130\uc758 \ubb36\uc778 \ucabd \ub05d
splitterSplit0Tip = \ubb36\uc778 \ucabd \ube44\ud2b8 \uc5c6\uc74c
splitterSplit1Tip = \ubb36\uc778 \ucabd\uc758 \ube44\ud2b8 %s
splitterSplitManyTip = \ubb36\uc778 \ucabd\uc758 \ube44\ud2b8 %s
# splitter attributes
splitterBitWidthAttr = \ubb36\uc778 \ucabd \ube44\ud2b8 \ud3ed
splitterFanOutAttr = \uac08\ub798
splitterBitAttr = \ube44\ud2b8 %s
splitterBitNone = \uc5c6\uc74c
splitterAppearanceAttr = \ubaa8\uc591
splitterAppearanceLegacy = \uc774\uc804 \ubc29\uc2dd
splitterAppearanceLeft = \uc67c\uc190\ud615
splitterAppearanceCenter = \uac00\uc6b4\ub370\ud615
splitterAppearanceRight = \uc624\ub978\uc190\ud615
splitterDistributeAscending = \uc624\ub984\ucc28\uc21c\uc73c\ub85c \ub098\ub204\uae30
splitterDistributeDescending = \ub0b4\ub9bc\ucc28\uc21c\uc73c\ub85c \ub098\ub204\uae30
#
# circuit/WireClass.java
#
wireComponent = \uc120
wireLengthAttr = \uae38\uc774
wireDirectionAttr = \ubc29\ud5a5
wireDirectionHorzOption = \uac00\ub85c
wireDirectionVertOption = \uc138\ub85c

# circuit/appear/AppearanceOrigin
circuitAnchor = \uae30\uc900\uc810
appearanceFacingAttr = \ubaa8\uc591 \ubc29\ud5a5

# circuit/appear/AppearancePort
circuitPort = \ud3ec\ud2b8
