#
# data/Attributes.java
#
booleanTrueOption = \uc608
booleanFalseOption = \uc544\ub2c8\uc694
#
# data/Direction.java
#
directionEastOption = \uc624\ub978\ucabd
directionWestOption = \uc67c\ucabd
directionNorthOption = \uc704
directionSouthOption = \uc544\ub798
directionNorthVertical = \uc704
directionSouthVertical = \uc544\ub798
directionEastVertical = \uc624\ub978\ucabd
directionWestVertical = \uc67c\ucabd
#
# data/Value.java
#
valueErrorSymbol = E
valueUnknownSymbol = x
valueError = Error
valueUnknown = ???
