# draw.model - Attributes
attrPaint = \uce60 \ubc29\uc2dd
attrFont = \uae00\uaf34
attrAlign = \uc815\ub82c
attrStrokeWidth = \uc120 \uad75\uae30
attrStroke = \uc120 \uc0c9
attrFill = \ucc44\uc6b0\uae30 \uc0c9
attrRx = \ubaa8\uc11c\ub9ac \ubc18\uc9c0\ub984
paintStroke = \ud14c\ub450\ub9ac\ub9cc
paintFill = \ucc44\uc6b0\uae30\ub9cc
paintBoth = \ud14c\ub450\ub9ac\uc640 \ucc44\uc6b0\uae30
alignStart = \uc67c\ucabd
alignMiddle = \uac00\uc6b4\ub370
alignEnd = \uc624\ub978\ucabd
# draw.model - CanvasObject names
shapeMultiple = \uac1c\uccb4
shapeCurve = \uace1\uc120
shapeRect = \uc0ac\uac01\ud615
shapeRoundRect = \ub465\uadfc \uc0ac\uac01\ud615
shapeOval = \ud0c0\uc6d0
shapePolygon = \ub2e4\uac01\ud615
shapePolyline = \uaebe\uc740\uc120
shapeLine = \uc9c1\uc120
shapeText = \ud14d\uc2a4\ud2b8
# draw.action - Action names
actionAdd = %s \ucd94\uac00
actionRemove = %s \uc0ad\uc81c
actionTranslate = %s \uc774\ub3d9
actionMoveHandle = \uc870\uc808\uc810 \uc774\ub3d9
actionInsertHandle = \uc870\uc808\uc810 \ucd94\uac00
actionDeleteHandle = \uc870\uc808\uc810 \uc0ad\uc81c
actionChangeAttributes = \uc18d\uc131 \ubc14\uafb8\uae30
actionChangeAttribute = %s \ubc14\uafb8\uae30
actionLower = \ub4a4\ub85c
actionRaise = \uc55e\uc73c\ub85c
actionReorder = \uc21c\uc11c \ubc14\uafb8\uae30
actionEditText = \ud14d\uc2a4\ud2b8 \ud3b8\uc9d1
# draw.gui - attribute table titles
selectionOne = \uc120\ud0dd: %s
selectionMultiple = \uc120\ud0dd: %s \u00d7 %s
selectionVarious = \uc120\ud0dd: \uc5ec\ub7ec \ud56d\ubaa9 \u00d7 %s
