#
# gui/AttributeTable.java
#
attributeDialogTitle = \uac12 \uc120\ud0dd
changeAttributeAction = \uc18d\uc131 \ubc14\uafb8\uae30
changeCircuitAttrAction = \ud68c\ub85c \uc18d\uc131 \ubc14\uafb8\uae30
attributeChangeInvalidError = \uc694\uccad\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc544 \uc18d\uc131\uc744 \ubc14\uafb8\uc9c0 \uc54a\uc558\uc2b5\ub2c8\ub2e4
attributeChangeInvalidTitle = \uc62c\ubc14\ub974\uc9c0 \uc54a\uc740 \uac12
cannotModifyCircuitError = \uc774 \ud68c\ub85c\ub294 \uc218\uc815\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
#
# gui/Canvas.java
#
canvasWidthError = \ube44\ud2b8 \ud3ed\uc774 \ub9de\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4
canvasOscillationError = \ubc1c\uc9c4\uc774 \uc77c\uc5b4\ub09c \uac83 \uac19\uc2b5\ub2c8\ub2e4
canvasExceptionError = \ub0b4\ubd80 \uc624\ub958\ub85c \uc2dc\ubbac\ub808\uc774\uc158\uc774 \uba48\ucdc4\uc2b5\ub2c8\ub2e4
#
# gui/Frame.java
#
titleCircFileKnown = Logisim: %s (%s)
titleFileKnown = Logisim: %s
confirmDiscardMessage = %s\uc758 \uc800\uc7a5\ud558\uc9c0 \uc54a\uc740 \ubcc0\uacbd \uc0ac\ud56d\uc744 \uc5b4\ub5bb\uac8c \ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?
confirmCloseTitle = \ub2eb\uae30 \ud655\uc778
saveOption = \uc800\uc7a5
discardOption = \ubc84\ub9ac\uae30
cancelOption = \ucde8\uc18c
#
# gui/ExportImage.java
#
labelCircuits = \ud68c\ub85c:
labelImageFormat = \uadf8\ub9bc \ud615\uc2dd:
labelScale = \ubc30\uc728:
labelPrinterView = \uc778\uc1c4\uc6a9 \ubcf4\uae30:
exportEmptyCircuitsTitle = \ub0b4\ubcf4\ub0bc \uc218 \uc5c6\uc74c
exportEmptyCircuitsMessage = \ub0b4\ubcf4\ub0bc \uc218 \uc788\ub294 \ud68c\ub85c\uac00 \uc5c6\uc2b5\ub2c8\ub2e4. \ubaa8\ub4e0 \ud68c\ub85c\uac00 \ube44\uc5b4 \uc788\uc2b5\ub2c8\ub2e4.
exportImageSelect = \uadf8\ub9bc\uc73c\ub85c \ub0b4\ubcf4\ub0b4\uae30
exportImageDirectorySelect = \ub0b4\ubcf4\ub0bc \ud3f4\ub354 \uc120\ud0dd
exportImageFileSelect = \ub0b4\ubcf4\ub0bc \ud30c\uc77c \uc120\ud0dd
exportImageButton = \ub0b4\ubcf4\ub0b4\uae30
exportGifFilter = GIF \ud30c\uc77c (*.gif)
exportPngFilter = PNG \ud30c\uc77c (*.png)
exportJpgFilter = JPEG \ud30c\uc77c (*.jpeg, *.jpg)
exportNewDirectoryErrorTitle = \ud3f4\ub354\ub97c \ub9cc\ub4e4 \uc218 \uc5c6\uc74c
exportNewDirectoryErrorMessage = \ud3f4\ub354\ub97c \ub9cc\ub4e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
couldNotCreateImage = \uadf8\ub9bc\uc744 \ub9cc\ub4e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
couldNotCreateFile = \ud30c\uc77c\uc744 \ub9cc\ub4e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
confirmOverwriteMessage = \ud30c\uc77c\uc774 \uc774\ubbf8 \uc788\uc2b5\ub2c8\ub2e4. \ub36e\uc5b4\uc4f0\uc2dc\uaca0\uc2b5\ub2c8\uae4c?
confirmOverwriteTitle = \ub36e\uc5b4\uc4f0\uae30 \ud655\uc778
exportImageProgress = \uadf8\ub9bc\uc744 \ub9cc\ub4dc\ub294 \uc911\u2026
#
# gui/Print.java
#
labelRotateToFit = \uc6a9\uc9c0\uc5d0 \ub9de\uac8c \ud68c\uc804:
labelHeader = \uba38\ub9ac\uae00:
printEmptyCircuitsTitle = \uc778\uc1c4\ud560 \uc218 \uc5c6\uc74c
printEmptyCircuitsMessage = \uc778\uc1c4\ud560 \uc218 \uc788\ub294 \ud68c\ub85c\uac00 \uc5c6\uc2b5\ub2c8\ub2e4. \ubaa8\ub4e0 \ud68c\ub85c\uac00 \ube44\uc5b4 \uc788\uc2b5\ub2c8\ub2e4.
printParmsTitle = \uc778\uc1c4 \uc124\uc815
printError = \uc778\uc1c4 \uc911 \uc624\ub958\uac00 \ub0ac\uc2b5\ub2c8\ub2e4: %s
printErrorTitle = \uc778\uc1c4 \uc624\ub958
#
# gui/SelectionActions.java
#
dropComponentAction = \ubd80\ud488 \ub193\uae30
dropComponentsAction = \ubd80\ud488 \uc5ec\ub7ec \uac1c \ub193\uae30
moveSelectionAction = \uc120\ud0dd \ud56d\ubaa9 \uc774\ub3d9
deleteSelectionAction = \uc120\ud0dd \ud56d\ubaa9 \uc0ad\uc81c
duplicateSelectionAction = \uc120\ud0dd \ud56d\ubaa9 \ubcf5\uc81c
cutSelectionAction = \uc120\ud0dd \ud56d\ubaa9 \uc798\ub77c\ub0b4\uae30
copySelectionAction = \uc120\ud0dd \ud56d\ubaa9 \ubcf5\uc0ac
pasteClipboardAction = \ud074\ub9bd\ubcf4\ub4dc \ubd99\uc5ec\ub123\uae30
pasteCloneQuery = \ud074\ub9bd\ubcf4\ub4dc\uc5d0 "%s"\uc774(\uac00) \uc788\uc2b5\ub2c8\ub2e4. \ud504\ub85c\uc81d\ud2b8\uc5d0\ub294 \uc774 \ubd80\ud488\uc774 \uc5c6\uc9c0\ub9cc \uc774\ub984\uc774 \uac19\uc740 \ub2e4\ub978 \ubd80\ud488\uc774 \uc788\uc2b5\ub2c8\ub2e4.
pasteCloneTitle = \ubd80\ud488
pasteCloneReplace = \ubc14\uafb8\uae30
pasteCloneIgnore = \ubb34\uc2dc
pasteCloneCancel = \ucde8\uc18c
pasteDropMessage = \ud504\ub85c\uc81d\ud2b8 \ub77c\uc774\ube0c\ub7ec\ub9ac\uac00 \uc9c0\uc6d0\ud558\uc9c0 \uc54a\uc544 \ud074\ub9bd\ubcf4\ub4dc\uc758 \uc77c\ubd80 \ubd80\ud488\uc744 \ubd99\uc5ec\ub123\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4:
pasteDropTitle = \ubd99\uc5ec\ub123\uc9c0 \ubabb\ud55c \ubd80\ud488
#
# tools/SelectionAttributeChange.java
#
selectionAttributeAction = \uc120\ud0dd \ud56d\ubaa9 \uc18d\uc131 \ubc14\uafb8\uae30
#
# tools/ToolActions.java
#
changeToolAttrAction = \ub3c4\uad6c \uc18d\uc131 \ubc14\uafb8\uae30
#
# gui/main/StatisticsDialog.java
#
statsDialogTitle = Logisim: %s \ud1b5\uacc4
statsCloseButton = \ub2eb\uae30
statsSimpleCountColumn = \ub2e8\uc21c \uac1c\uc218
statsUniqueCountColumn = \uace0\uc720 \uac1c\uc218
statsRecursiveCountColumn = \uc7ac\uadc0 \uac1c\uc218
statsComponentColumn = \ubd80\ud488
statsLibraryColumn = \ub77c\uc774\ube0c\ub7ec\ub9ac
statsTotalWithout = \ud569\uacc4 (\ud504\ub85c\uc81d\ud2b8 \ud558\uc704 \ud68c\ub85c \uc81c\uc678)
statsTotalWith = \ud569\uacc4 (\ud558\uc704 \ud68c\ub85c \ud3ec\ud568)
#
# gui/main/ExplorerToolbarModel.java
#
projectViewToolboxTip = \ud0d0\uc0c9 \ucc3d\uc5d0 \ud504\ub85c\uc81d\ud2b8\uc758 \ud68c\ub85c\uc640 \ub77c\uc774\ube0c\ub7ec\ub9ac \ud45c\uc2dc
projectViewSimulationTip = \ud0d0\uc0c9 \ucc3d\uc5d0 \uc2dc\ubbac\ub808\uc774\uc158 \uacc4\uce35 \ud45c\uc2dc
projectEditLayoutTip = \ubcf4\uace0 \uc788\ub294 \ud68c\ub85c\uc758 \ubc30\uce58 \ud3b8\uc9d1
projectEditAppearanceTip = \ubcf4\uace0 \uc788\ub294 \ud68c\ub85c\uc758 \ud558\uc704 \ud68c\ub85c \ubaa8\uc591 \ud3b8\uc9d1
#
# gui/main/ToolboxToolbarModel.java
#
projectAddCircuitTip = \ud68c\ub85c \ucd94\uac00
projectMoveCircuitDownTip = \ubcf4\uace0 \uc788\ub294 \ud68c\ub85c\ub97c \ubaa9\ub85d\uc5d0\uc11c \uc544\ub798\ub85c \uc774\ub3d9
projectMoveCircuitUpTip = \ubcf4\uace0 \uc788\ub294 \ud68c\ub85c\ub97c \ubaa9\ub85d\uc5d0\uc11c \uc704\ub85c \uc774\ub3d9
projectRemoveCircuitTip = \ubcf4\uace0 \uc788\ub294 \ud68c\ub85c \uc0ad\uc81c
#
# gui/main/SimulationToolbarModel.java
#
simulateEnableStepsTip = \ud68c\ub85c\uc758 \uc2e0\ud638 \uc804\ud30c \ucf1c\uae30
simulateDisableStepsTip = \ud68c\ub85c\uc758 \uc2e0\ud638 \uc804\ud30c \ub044\uae30
simulateStepTip = \ud68c\ub85c\uc758 \uc2e0\ud638\ub97c \ud55c \ub2e8\uacc4 \uc804\ud30c
simulateEnableTicksTip = \ud074\ub7ed \ud2f1 \ucf1c\uae30
simulateDisableTicksTip = \ud074\ub7ed \ud2f1 \ub044\uae30
simulateTickTip = \ud074\ub7ed \ud55c \ubc88 \ud2f1
#
# gui/TickRate.java
#
tickRateHz = %s Hz
tickRateKHz = %s KHz
#
# gui/ZoomControl.java
#
zoomShowGrid = \uaca9\uc790 \ud45c\uc2dc \ucf1c\uae30/\ub044\uae30
#
# gui/appear/RevertAppearanceAction
#
revertAppearanceAction = \ubaa8\uc591 \ub418\ub3cc\ub9ac\uae30
#
# attribute table models
#
circuitAttrTitle = \ud68c\ub85c: %s
toolAttrTitle = \ub3c4\uad6c: %s
selectionOne = \uc120\ud0dd: %s
selectionMultiple = \uc120\ud0dd: %s \u00d7 %s
selectionVarious = \uc120\ud0dd: \uc5ec\ub7ec \uc885\ub958 \u00d7 %s
