#
# OptionsFrame.java
#
logFrameTitle = Logisim: %s \uae30\ub85d (%s)
logFrameMenuItem = %s: \uae30\ub85d
closeButton = \ucc3d \ub2eb\uae30
#
# SelectionPanel.java
#
selectionTab = \uc120\ud0dd
selectionHelp = \uac12\uc744 \uae30\ub85d\ud560 \ubd80\ud488\uc744 \uace0\ub985\ub2c8\ub2e4.
selectionAdd = \ucd94\uac00 >>
selectionChangeBase = \uc9c4\ubc95 \ubc14\uafb8\uae30
selectionMoveUp = \uc704\ub85c
selectionMoveDown = \uc544\ub798\ub85c
selectionRemove = << \uc81c\uac70
#
# TablePanel.java
#
tableTab = \ud45c
tableHelp = \ucd5c\uadfc \uac12\uc758 \uae30\ub85d\uc744 \ubd05\ub2c8\ub2e4.
tableEmptyMessage = \uc120\ud0dd\ud55c \ud56d\ubaa9\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.
#
# FilePanel.java
#
fileTab = \ud30c\uc77c
fileHelp = \ud30c\uc77c \ucd9c\ub825\uc744 \uc124\uc815\ud569\ub2c8\ub2e4.
fileEnabled = \ud30c\uc77c \ucd9c\ub825\uc774 \ucf1c\uc838 \uc788\uc2b5\ub2c8\ub2e4.
fileDisabled = \ud30c\uc77c \ucd9c\ub825\uc774 \uaebc\uc838 \uc788\uc2b5\ub2c8\ub2e4.
fileEnableButton = \ucf1c\uae30
fileDisableButton = \ub044\uae30
fileLabel = \ud30c\uc77c:
fileSelectButton = \uc120\ud0dd\u2026
fileHeaderCheck = \uba38\ub9ac\uae00 \uc904 \ub123\uae30
fileCannotWriteTitle = \ud30c\uc77c\uc744 \uc4f8 \uc218 \uc5c6\uc74c
fileCannotWriteMessage = "%s"\uc5d0 \uc4f8 \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.
fileExistsTitle = \ud30c\uc77c\uc774 \uc774\ubbf8 \uc788\uc74c
fileExistsMessage = "%s" \ud30c\uc77c\uc774 \uc774\ubbf8 \uc788\uc2b5\ub2c8\ub2e4.
fileOverwriteOption = \ub36e\uc5b4\uc4f0\uae30
fileAppendOption = \uc774\uc5b4 \uc4f0\uae30
fileCancelOption = \ucde8\uc18c
