#
# OptionsFrame.java
#
optionsFrameTitle = Logisim: %s \uc635\uc158
optionsFrameMenuItem = %s: \uc635\uc158
revertButton = \ubaa8\ub450 \ud15c\ud50c\ub9bf \uac12\uc73c\ub85c \ub418\ub3cc\ub9ac\uae30
closeButton = \ucc3d \ub2eb\uae30
#
# OptionsActions.java
#
setOptionAction = %s \uc124\uc815
addMouseMappingAction = \ub9c8\uc6b0\uc2a4 \ub9e4\ud551 \ucd94\uac00
removeMouseMappingAction = \ub9c8\uc6b0\uc2a4 \ub9e4\ud551 \uc0ad\uc81c
#
# SimulateOptions.java
#
simulateTitle = \uc2dc\ubbac\ub808\uc774\uc158
simulateHelp = \ud68c\ub85c \ub3d9\uc791\uc744 \uc2dc\ubbac\ub808\uc774\uc158\ud558\ub294 \uc5d4\uc9c4\uc744 \uc124\uc815\ud569\ub2c8\ub2e4.
simulateLimit = \ubc1c\uc9c4\uc73c\ub85c \ud310\ub2e8\ud560 \ubc18\ubcf5 \ud69f\uc218
gateUndefined = \uc785\ub825\uc774 \uc815\ud574\uc9c0\uc9c0 \uc54a\uc558\uc744 \ub54c \uac8c\uc774\ud2b8 \ucd9c\ub825
simulateRandomness = \ubd80\ud488 \uc9c0\uc5f0\uc5d0 \uc7a1\uc74c \ub354\ud558\uae30
#
# MouseOptions.java
#
mouseTitle = \ub9c8\uc6b0\uc2a4
mouseHelp = \ub9c8\uc6b0\uc2a4 \ubc84\ud2bc\uc5d0 \uc9c0\uc815\ud560 \ub3c4\uad6c\ub97c \ud3b8\uc9d1\ud569\ub2c8\ub2e4.
mouseMapNone = \uc120\ud0dd\ud55c \ub3c4\uad6c \uc5c6\uc74c
mouseMapText = \uc6d0\ud558\ub294 \ubc84\ud2bc\u00b7\ud0a4 \uc870\ud569\uc73c\ub85c \ud074\ub9ad\ud558\uba74
mouseMapText2 = %s\uc744(\ub97c) \uadf8 \uc870\ud569\uc5d0 \uc9c0\uc815\ud569\ub2c8\ub2e4
mouseRemoveButton = \uc0ad\uc81c
#
# ToolbarOptions.java
#
toolbarTitle = \ub3c4\uad6c \ubaa8\uc74c
toolbarHelp = \ub3c4\uad6c \ubaa8\uc74c\uc5d0 \ub098\uc62c \ub3c4\uad6c\ub97c \ud3b8\uc9d1\ud569\ub2c8\ub2e4.
toolbarAddTool = \ub3c4\uad6c \ucd94\uac00
toolbarAddSeparator = \uad6c\ubd84\uc120 \ucd94\uac00
toolbarMoveUp = \uc704\ub85c \uc774\ub3d9
toolbarMoveDown = \uc544\ub798\ub85c \uc774\ub3d9
toolbarRemove = \uc0ad\uc81c
#
# ToolbarActions.java
#
toolbarAddAction = \ub3c4\uad6c \ubaa8\uc74c \ubc84\ud2bc \ucd94\uac00
toolbarRemoveAction = \ub3c4\uad6c \ubaa8\uc74c \ubc84\ud2bc \uc0ad\uc81c
toolbarMoveAction = \ub3c4\uad6c \ubaa8\uc74c \ubc84\ud2bc \uc774\ub3d9
toolbarInsertSepAction = \uad6c\ubd84\uc120 \ub123\uae30
toolbarRemoveSepAction = \uad6c\ubd84\uc120 \uc0ad\uc81c
