#
# PreferencesFrame.java
#
preferencesFrameTitle = Logisim: \ud658\uacbd\uc124\uc815
preferencesFrameMenuItem = \ud658\uacbd\uc124\uc815
closeButton = \ucc3d \ub2eb\uae30

# TemplateOptions.java
templateTitle = \ud15c\ud50c\ub9bf
templateHelp = \ud604\uc7ac \ud15c\ud50c\ub9bf \uc120\ud0dd
templatePlainOption = \uae30\ubcf8 \ud15c\ud50c\ub9bf
templateEmptyOption = \ube48 \ud15c\ud50c\ub9bf
templateCustomOption = \uc0ac\uc6a9\uc790 \ud15c\ud50c\ub9bf:
templateSelectButton = \uc120\ud0dd\u2026
templateErrorMessage = \ud15c\ud50c\ub9bf\uc744 \ubd88\ub7ec\uc62c \uc218 \uc5c6\uc2b5\ub2c8\ub2e4: %s
templateErrorTitle = \ud15c\ud50c\ub9bf \ubd88\ub7ec\uc624\uae30 \uc624\ub958
selectDialogTitle = \ud15c\ud50c\ub9bf \uc120\ud0dd
selectDialogButton = \uc120\ud0dd

# IntlOptions.java
intlTitle = \uc5b8\uc5b4
intlHelp = \uc5b8\uc5b4\uc640 \uc9c0\uc5ed \uc124\uc815 \ud3b8\uc9d1
intlLocale = \uc5b8\uc5b4:
intlReplaceAccents = \uc545\uc13c\ud2b8\uac00 \ubd99\uc740 \uae00\uc790\ub97c \uc77c\ubc18 \uae00\uc790\ub85c \ubc14\uafb8\uae30
intlGateShape = \uac8c\uc774\ud2b8 \ubaa8\uc591:
shapeShaped = \ud2b9\uc9d5\ud615
shapeRectangular = \uc0ac\uac01\ud615
shapeDIN40700 = DIN 40700

# WindowOptions.java
windowTitle = \ucc3d
windowHelp = \uc8fc \ud3b8\uc9d1 \ucc3d \uc124\uc815
windowTickRate = \ud2f1 \uc18d\ub3c4 \ud45c\uc2dc
windowToolbarLocation = \ub3c4\uad6c \ubaa8\uc74c \uc704\uce58:
windowToolbarHidden = \uc228\uae40
windowToolbarDownMiddle = \uac00\uc6b4\ub370 \uc138\ub85c

# LayoutOptions.java
layoutTitle = \ubc30\uce58
layoutHelp = \ubc30\uce58 \ud3b8\uc9d1\uae30 \ub3d9\uc791 \uc124\uc815
layoutAddShowGhosts = \ucd94\uac00\ud560 \ub54c \ubbf8\ub9ac\ubcf4\uae30 \ud45c\uc2dc
layoutPrinterView = \uc778\uc1c4\uc6a9 \ubcf4\uae30
layoutMoveKeepConnect = \uc774\ub3d9\ud560 \ub54c \uc5f0\uacb0 \uc720\uc9c0
layoutAttributeHalo = \uc18d\uc131 \ud45c\uc5d0 \ud45c\uc2dc \uc911\uc778 \ubd80\ud488 \uac15\uc870
layoutShowTips = \ubd80\ud488 \ub3c4\uc6c0\ub9d0 \ud45c\uc2dc
layoutAddAfter = \ubd80\ud488\uc744 \ucd94\uac00\ud55c \ub4a4:
layoutAddAfterUnchanged = \ubd80\ud488 \ub3c4\uad6c \uc720\uc9c0
layoutAddAfterEdit = \ud3b8\uc9d1 \ub3c4\uad6c\ub85c \ubc14\uafb8\uae30
layoutRadix1 = \uc870\uc791 \ub3c4\uad6c\ub85c \uc120\uc744 \ub204\ub97c \ub54c \uccab\uc9f8 \uc9c4\ubc95:
layoutRadix2 = \uc870\uc791 \ub3c4\uad6c\ub85c \uc120\uc744 \ub204\ub97c \ub54c \ub458\uc9f8 \uc9c4\ubc95:

# ExperimentalOptions.java
experimentTitle = \uc2e4\ud5d8 \uae30\ub2a5
experimentHelp = \uc544\uc9c1 \ucda9\ubd84\ud788 \uc2dc\ud5d8\ud558\uc9c0 \uc54a\uc740 \uae30\ub2a5 \ucf1c\uae30
accelLabel = \uadf8\ub798\ud53d \uac00\uc18d:
accelDefault = \uae30\ubcf8\uac12 \uc0ac\uc6a9
accelNone = \uc5c6\uc74c
accelOpenGL = OpenGL
accelD3D = Direct 3D
accelRestartLabel = \ubc14\uafbc \uc124\uc815\uc740 Logisim\uc744 \ub2e4\uc2dc \uc2dc\uc791\ud574\uc57c \uc801\uc6a9\ub429\ub2c8\ub2e4.
