#
# tools/AddTool.java
#
addToolText = %s \ucd94\uac00
negativeCoordError = \ubd80\ud488\uc758 \uc88c\ud45c\ub294 \uc74c\uc218\uc77c \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
cannotModifyError = \ud68c\ub85c\ub97c \uc218\uc815\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
circularError = \uc21c\ud658 \ucc38\uc870\ub97c \ub9cc\ub4e4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.
exclusiveError = \uadf8 \uc790\ub9ac\uc5d0 \uacb9\uce58\ub294 \ubd80\ud488\uc774 \uc774\ubbf8 \uc788\uc2b5\ub2c8\ub2e4.
addComponentAction = %s \ucd94\uac00
#
# tools/MenuTool.java
#
menuTool = \uba54\ub274 \ub3c4\uad6c
menuToolDesc = \ubd80\ud488 \uba54\ub274 \ubcf4\uae30
compDeleteItem = \uc0ad\uc81c
compShowAttrItem = \uc18d\uc131 \ubcf4\uae30
selDeleteItem = \uc120\ud0dd \uc601\uc5ed \uc0ad\uc81c
selCutItem = \uc120\ud0dd \uc601\uc5ed \uc798\ub77c\ub0b4\uae30
selCopyItem = \uc120\ud0dd \uc601\uc5ed \ubcf5\uc0ac
removeComponentAction = %s \uc0ad\uc81c
#
# tools/PokeTool.java
#
pokeTool = \uc870\uc791 \ub3c4\uad6c
pokeToolDesc = \ud68c\ub85c \uc548\uc758 \uac12 \ubc14\uafb8\uae30
#
# tools/SelectTool.java
#
selectTool = \uc120\ud0dd \ub3c4\uad6c
selectToolDesc = \ud68c\ub85c \ubd80\ud488 \ud3b8\uc9d1
moveWorkingMsg = \uc5f0\uacb0\uc744 \uacc4\uc0b0\ud558\ub294 \uc911\u2026
#
# tools/SelectionAttributeChange.java
#
selectionRefaceAction = \uc120\ud0dd \uc601\uc5ed \ubc29\ud5a5 \ubc14\uafb8\uae30
#
# tools/key/KeyConfigurationAction
#
changeComponentAttributesAction = \ubd80\ud488 \uc18d\uc131 \ubc14\uafb8\uae30
#
# tools/TextTool.java
#
textTool = \ud14d\uc2a4\ud2b8 \ub3c4\uad6c
textToolDesc = \ud68c\ub85c\uc758 \ud14d\uc2a4\ud2b8 \ud3b8\uc9d1
#
# tools/EditTool.java
#
editTool = \ud3b8\uc9d1 \ub3c4\uad6c
editToolDesc = \uc120\ud0dd \uc601\uc5ed \ud3b8\uc9d1\uacfc \uc120 \ucd94\uac00
#
# tools/WiringTool.java
#
wiringTool = \ubc30\uc120 \ub3c4\uad6c
wiringToolDesc = \ud68c\ub85c\uc5d0 \uc120 \ucd94\uac00
addWireAction = \uc120 \ucd94\uac00
addWiresAction = \uc120 \uc5ec\ub7ec \uac1c \ucd94\uac00
shortenWireAction = \uc120 \uc904\uc774\uae30
