#
# util/FontUtil.java
#
fontPlainStyle = \ubcf4\ud1b5
fontBoldStyle = \uad75\uac8c
fontItalicStyle = \uae30\uc6b8\uc784
fontBoldItalicStyle = \uad75\uc740 \uae30\uc6b8\uc784
#
# util/InputEventUtil.java
#
metaMod = Meta
altMod = Alt
ctrlMod = Ctrl
shiftMod = Shift
button1Mod = \ubc84\ud2bc1
button2Mod = \ubc84\ud2bc2
button3Mod = \ubc84\ud2bc3
#
# util/JDialogOk.java
#
dlogOkButton = \ud655\uc778
dlogCancelButton = \ucde8\uc18c
#
# util/LocaleManager.java
#
# If the user selects to "replace accented characters" in the International
# dialog, the program will replace accented characters based on
# the slash-delimited character-string pairs in accentReplacements.
# For example, with German, accentReplacements might be
# "\u00f6 oe/\u00d6 Oe/\u00fc ue/\u00dc ue/\u00df ss" so that umlauted o's and u's are
# replaced, as would be essets.
accentReplacements =
#
# util/GifEncoder.java
#
grabberError = \uc774\ubbf8\uc9c0 \ucea1\ucc98\uac00 false\ub97c \ubc18\ud658\ud588\uc2b5\ub2c8\ub2e4: 
manyColorError = \uc0c9\uc774 \ub108\ubb34 \ub9ce\uc2b5\ub2c8\ub2e4.
#
# util/WindowMenu.java
#
windowMenu = \ucc3d
windowMinimizeItem = \ucd5c\uc18c\ud654
windowZoomItem = \ucd5c\ub300\ud654
windowZoomItemMac = \ud655\ub300/\ucd95\uc18c
windowCloseItem = \ub2eb\uae30
