/* Generated by engine/src/test/java/kr/ac/hallym/hcs/engine/ToolArgsTest.java -- do not edit.
   What the number after a name sets (the search palette, the Components search;
   v1 Palette.attributesFor, D-150): a gate's number of inputs, a splitter's incoming
   width, a constant's value after 0x, else the width.  Key: library/tool as
   model.library names them.  A tool not here takes no number (it is listed as it is).
   The engine's test checks this file against the tools' own attributes. */

export interface ToolArg {
  attr: string;        // the .circ attribute the number sets
  label: string;       // its name in the attribute table (English)
  min: number;         // the numbers the original accepts
  max: number;
  hex?: string;        // after 0x: this attribute, the text as typed (a constant's value)
}

export const TOOL_ARGS: Readonly<Record<string, ToolArg>> = {
  'Gates/NOT Gate': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Gates/Buffer': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Gates/AND Gate': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/OR Gate': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/NAND Gate': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/NOR Gate': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/XOR Gate': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/XNOR Gate': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/Odd Parity': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/Even Parity': { attr: 'inputs', label: 'Number Of Inputs', min: 2, max: 32 },
  'Gates/Controlled Buffer': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Gates/Controlled Inverter': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Wiring/Splitter': { attr: 'incoming', label: 'Bit Width In', min: 1, max: 32 },
  'Wiring/Pin': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Wiring/Tunnel': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Wiring/Constant': { attr: 'width', label: 'Data Bits', min: 1, max: 32, hex: 'value' },
  'Wiring/Power': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Wiring/Ground': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Wiring/Transistor': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Wiring/Transmission Gate': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Plexers/Multiplexer': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Plexers/Demultiplexer': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Plexers/BitSelector': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Adder': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Subtractor': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Multiplier': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Divider': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Negator': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Comparator': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/Shifter': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/BitAdder': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Arithmetic/BitFinder': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Memory/Register': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Memory/Counter': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Memory/Shift Register': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Memory/Random': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
  'Memory/RAM': { attr: 'dataWidth', label: 'Data Bit Width', min: 1, max: 32 },
  'Memory/ROM': { attr: 'dataWidth', label: 'Data Bit Width', min: 1, max: 32 },
  'kr.ac.hallym.hcs.mips.MipsLibrary/Radix Probe': { attr: 'width', label: 'Data Bits', min: 1, max: 32 },
};
