# Instructions SPIM lists differently when assembled than as a .word (D-127).
# Generated by tools/gen-disasm-golden.sh. Do not edit.
	.text
main:
	c.f.s $f0, $f2
	c.f.s 1, $f30, $f4
	c.f.s 7, $f2, $f31
	c.f.s 0, $f4, $f6
	c.f.d $f0, $f2
	c.f.d 1, $f30, $f4
	c.f.d 7, $f2, $f31
	c.f.d 0, $f4, $f6
	c.un.s $f0, $f2
	c.un.s 1, $f30, $f4
	c.un.s 7, $f2, $f31
	c.un.s 0, $f4, $f6
	c.un.d $f0, $f2
	c.un.d 1, $f30, $f4
	c.un.d 7, $f2, $f31
	c.un.d 0, $f4, $f6
	c.eq.s $f0, $f2
	c.eq.s 1, $f30, $f4
	c.eq.s 7, $f2, $f31
	c.eq.s 0, $f4, $f6
	c.eq.d $f0, $f2
	c.eq.d 1, $f30, $f4
	c.eq.d 7, $f2, $f31
	c.eq.d 0, $f4, $f6
	c.ueq.s $f0, $f2
	c.ueq.s 1, $f30, $f4
	c.ueq.s 7, $f2, $f31
	c.ueq.s 0, $f4, $f6
	c.ueq.d $f0, $f2
	c.ueq.d 1, $f30, $f4
	c.ueq.d 7, $f2, $f31
	c.ueq.d 0, $f4, $f6
	c.olt.s $f0, $f2
	c.olt.s 1, $f30, $f4
	c.olt.s 7, $f2, $f31
	c.olt.s 0, $f4, $f6
	c.olt.d $f0, $f2
	c.olt.d 1, $f30, $f4
	c.olt.d 7, $f2, $f31
	c.olt.d 0, $f4, $f6
	c.ult.s $f0, $f2
	c.ult.s 1, $f30, $f4
	c.ult.s 7, $f2, $f31
	c.ult.s 0, $f4, $f6
	c.ult.d $f0, $f2
	c.ult.d 1, $f30, $f4
	c.ult.d 7, $f2, $f31
	c.ult.d 0, $f4, $f6
	c.ole.s $f0, $f2
	c.ole.s 1, $f30, $f4
	c.ole.s 7, $f2, $f31
	c.ole.s 0, $f4, $f6
	c.ole.d $f0, $f2
	c.ole.d 1, $f30, $f4
	c.ole.d 7, $f2, $f31
	c.ole.d 0, $f4, $f6
	c.ule.s $f0, $f2
	c.ule.s 1, $f30, $f4
	c.ule.s 7, $f2, $f31
	c.ule.s 0, $f4, $f6
	c.ule.d $f0, $f2
	c.ule.d 1, $f30, $f4
	c.ule.d 7, $f2, $f31
	c.ule.d 0, $f4, $f6
	c.sf.s $f0, $f2
	c.sf.s 1, $f30, $f4
	c.sf.s 7, $f2, $f31
	c.sf.s 0, $f4, $f6
	c.sf.d $f0, $f2
	c.sf.d 1, $f30, $f4
	c.sf.d 7, $f2, $f31
	c.sf.d 0, $f4, $f6
	c.ngle.s $f0, $f2
	c.ngle.s 1, $f30, $f4
	c.ngle.s 7, $f2, $f31
	c.ngle.s 0, $f4, $f6
	c.ngle.d $f0, $f2
	c.ngle.d 1, $f30, $f4
	c.ngle.d 7, $f2, $f31
	c.ngle.d 0, $f4, $f6
	c.seq.s $f0, $f2
	c.seq.s 1, $f30, $f4
	c.seq.s 7, $f2, $f31
	c.seq.s 0, $f4, $f6
	c.seq.d $f0, $f2
	c.seq.d 1, $f30, $f4
	c.seq.d 7, $f2, $f31
	c.seq.d 0, $f4, $f6
	c.ngl.s $f0, $f2
	c.ngl.s 1, $f30, $f4
	c.ngl.s 7, $f2, $f31
	c.ngl.s 0, $f4, $f6
	c.ngl.d $f0, $f2
	c.ngl.d 1, $f30, $f4
	c.ngl.d 7, $f2, $f31
	c.ngl.d 0, $f4, $f6
	c.lt.s $f0, $f2
	c.lt.s 1, $f30, $f4
	c.lt.s 7, $f2, $f31
	c.lt.s 0, $f4, $f6
	c.lt.d $f0, $f2
	c.lt.d 1, $f30, $f4
	c.lt.d 7, $f2, $f31
	c.lt.d 0, $f4, $f6
	c.nge.s $f0, $f2
	c.nge.s 1, $f30, $f4
	c.nge.s 7, $f2, $f31
	c.nge.s 0, $f4, $f6
	c.nge.d $f0, $f2
	c.nge.d 1, $f30, $f4
	c.nge.d 7, $f2, $f31
	c.nge.d 0, $f4, $f6
	c.le.s $f0, $f2
	c.le.s 1, $f30, $f4
	c.le.s 7, $f2, $f31
	c.le.s 0, $f4, $f6
	c.le.d $f0, $f2
	c.le.d 1, $f30, $f4
	c.le.d 7, $f2, $f31
	c.le.d 0, $f4, $f6
	c.ngt.s $f0, $f2
	c.ngt.s 1, $f30, $f4
	c.ngt.s 7, $f2, $f31
	c.ngt.s 0, $f4, $f6
	c.ngt.d $f0, $f2
	c.ngt.d 1, $f30, $f4
	c.ngt.d 7, $f2, $f31
	c.ngt.d 0, $f4, $f6
	movf.s $f0, $f2, 0
	movf.s $f4, $f2, 3
	movf.s $f30, $f31, 7
	movf.d $f0, $f2, 0
	movf.d $f4, $f2, 3
	movf.d $f30, $f31, 7
	movt.s $f0, $f2, 0
	movt.s $f4, $f2, 3
	movt.s $f30, $f31, 7
	movt.d $f0, $f2, 0
	movt.d $f4, $f2, 3
	movt.d $f30, $f31, 7
	movz.s $f4, $f2, $t1
	movz.s $f0, $f0, $0
	movz.s $f30, $f31, $31
	movz.d $f4, $f2, $t1
	movz.d $f0, $f0, $0
	movz.d $f30, $f31, $31
	movn.s $f4, $f2, $t1
	movn.s $f0, $f0, $0
	movn.s $f30, $f31, $31
	movn.d $f4, $f2, $t1
	movn.d $f0, $f0, $0
	movn.d $f30, $f31, $31
	trunc.w.s $f0, $f2
	trunc.w.s $f31, $f1
	trunc.w.s $f4, $f30
	bc1f main
	bc1f 3, fwd
	bc1f 7, main
	bc1t main
	bc1t 3, fwd
	bc1t 7, main
	bc1fl main
	bc1fl 3, fwd
	bc1fl 7, main
	bc1tl main
	bc1tl 3, fwd
	bc1tl 7, main
	bc2f main
	bc2f 3, fwd
	bc2f 7, main
	bc2t main
	bc2t 3, fwd
	bc2t 7, main
	bc2fl main
	bc2fl 3, fwd
	bc2fl 7, main
	bc2tl main
	bc2tl 3, fwd
	bc2tl 7, main
	movf $3, $2, 1
	movf $31, $31, 7
	movf $0, $0, 0
	movf $8, $9, 4
	movt $3, $2, 1
	movt $31, $31, 7
	movt $0, $0, 0
	movt $8, $9, 4
fwd:
	jr $31
